UPDATE `centros` SET `telefono2` = '664142928', `correo_electronico` = 'info@asindi.org' WHERE (`id` = '2');
UPDATE `centros` SET `telefono2` = '657813847' WHERE (`id` = '3');
UPDATE `centros` SET `nombre` = 'ASOCIACION VERA PLENA INCLUSION' WHERE (`id` = '6');
UPDATE `centros` SET `telefono2` = '671006164', `correo_electronico` = 'alex.roman@aspacecaceres.es' WHERE (`id` = '8');
UPDATE `centros` SET `nombre` = 'RESIDENCIAL BANIUM', `tipo_via` = 'CALLE', `tipo_via_id` = '20', `direccion` = 'DEL BAÑO', `numero` = 'S/N' WHERE (`id` = '10');
UPDATE `centros` SET `correo_electronico` = 'camf.alcuescar@imserso.es' WHERE (`id` = '12');
UPDATE `centros` SET `telefono` = '924021564', `telefono2` = '' WHERE (`id` = '13');
UPDATE `centros` SET `nombre` = 'CENTRO RESIDENCIAL HOGARES LA VIRREINA - FUNDACION AUTISMO SUR', `poblacion` = 'PALMA-PALMILLA' WHERE (`id` = '14');
UPDATE `centros` SET `nombre` = 'CENTRO RESIDENCIAL MARIA JESUS LOPEZ HERRERO', `direccion` = 'DE FRANCISCO PANIAGUA LOAISA', `numero` = 'S/N' WHERE (`id` = '15');
UPDATE `centros` SET `nombre` = 'CENTRO ATENCION MENORES PEDRO DE VALDIVIA' WHERE (`id` = '16');
UPDATE `centros` SET `correo_electronico` = 'gestion.casadelamisericordia@gmail.com' WHERE (`id` = '17');
UPDATE `centros` SET `nombre` = 'CASER RESIDENCIAL OLIVENZA', `telefono` = '924492890' WHERE (`id` = '20');
UPDATE `centros` SET `direccion` = 'DEL GUADIANA' WHERE (`id` = '21');
UPDATE `centros` SET `nombre` = 'CARITAS, CENTRO DE ACOGIDA TEMPORAL PLASENCIA', `planta` = 'B', `letra` = 'B' WHERE (`id` = '24');
UPDATE `centros` SET `nombre` = 'CENTRO DE MAYORES VIRGEN DE LA PIEDAD EL TORNO', `tipo_via` = 'AVENIDA', `tipo_via_id` = '10' WHERE (`id` = '26');
UPDATE `centros` SET `nombre` = 'CENTRO ACOGIDA MENORES FRANCISCO PIZARRO' WHERE (`id` = '27');
UPDATE `centros` SET `nombre` = 'CENTRO ATENCION MENORES ANA BOLAÑOS' WHERE (`id` = '11');
UPDATE `centros` SET `nombre` = 'CENTRO ACOGIDA MENORES ISABEL DE MOCTEZUMA' WHERE (`id` = '28');
UPDATE `centros` SET `direccion` = 'DE CACERES', `numero` = 'KM. 7,5' WHERE (`id` = '29');
UPDATE `centros` SET `nombre` = 'CENTRO ACOGIDA PADRE CRISTOBAL' WHERE (`id` = '30');
UPDATE `centros` SET `tipo_via` = 'ARRABAL', `tipo_via_id` = '' WHERE (`id` = '34');
UPDATE `centros` SET `nombre` = 'CENTRO PENITENCIARIO ALICANTE HOSPITAL PSIQUIATRICO', `tipo_via` = 'POLIGONO', `tipo_via_id` = '49', `direccion` = 'DE LA VALLONGA' WHERE (`id` = '37');
UPDATE `centros` SET `nombre` = 'HOSPITAL PUBLICO PSIQUIATRICO PENITENCIARIO' WHERE (`id` = '38');
UPDATE `centros` SET `tipo_via` = 'CALLE', `tipo_via_id` = '20', `direccion` = 'HUERTAS', `numero` = '16' WHERE (`id` = '48');

INSERT INTO `tipos_via` (`nombre`) VALUES ('ARRABAL');

UPDATE `centros` SET `tipo_via` = 'ARRABAL', `tipo_via_id` = '84' WHERE (`id` = '34');
UPDATE `centros` SET `nombre` = 'CENTRO RESIDENCIAL REAL DE NAVALMORAL' WHERE (`id` = '51');
UPDATE `centros` SET `direccion` = 'CERVANTES' WHERE (`id` = '54');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE ANCIANOS SAN FRANCISCO' WHERE (`id` = '57');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE MAYORES SAN MIGUEL' WHERE (`id` = '58');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE MAYORES TORRECILLA' WHERE (`id` = '59');
UPDATE `centros` SET `direccion` = 'VALVERDE DE MERIDA', `numero` = '101' WHERE (`id` = '61');
UPDATE `centros` SET `telefono` = '654911689' WHERE (`id` = '66');
UPDATE `centros` SET `direccion` = 'MIGUEL DE UNAMUNO', `numero` = '1' WHERE (`id` = '70');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE MAYORES SANTA ISABEL' WHERE (`id` = '73');
UPDATE `centros` SET `direccion` = 'HOSPITAL DE SANTIAGO' WHERE (`id` = '76');
UPDATE `centros` SET `nombre` = 'INCLUDES ALMENDRALEJO', `tipo_via` = 'CARRETERA', `tipo_via_id` = '27', `direccion` = 'FUENTE DEL MAESTRE', `numero` = 'S/N' WHERE (`id` = '77');
UPDATE `centros` SET `direccion` = 'HABA', `numero` = '' WHERE (`id` = '78');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION AZUAGA (APROSUBA 10)' WHERE (`id` = '86');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION BADAJOZ (APROSUBA 3)' WHERE (`id` = '87');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION CABEZA DEL BUEY (APROSUBA 11)' WHERE (`id` = '88');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION LLERENA (APROSUBA 6)' WHERE (`id` = '89');
UPDATE `centros` SET `nombre` = 'PLENA INCLUISION MERIDA (APROSUBA 7)' WHERE (`id` = '90');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION MONTIJO (APROSUBA 8)' WHERE (`id` = '91');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION PUEBLA DE ALCOCER' WHERE (`id` = '92');
UPDATE `centros` SET `nombre` = 'PLENA INCLUSION ZAFRA (APROSUBA 1)' WHERE (`id` = '93');
UPDATE `centros` SET `direccion` = 'MASSENET', `poblacion` = 'MALAGA' WHERE (`id` = '14');
UPDATE `centros` SET `tipo_via` = 'AVENIDA', `tipo_via_id` = '10', `telefono` = '927306122' WHERE (`id` = '104');
UPDATE `centros` SET `nombre` = 'PISOS TUTELADOS DE FREGENAL DE LA SIERRA, HOGAR DE SAN BLAS' WHERE (`id` = '106');
UPDATE `centros` SET `nombre` = 'PISOS TUTELADOS DE GUIJO DE GRANADILLA,CENTRO DE DIA' WHERE (`id` = '107');
UPDATE `centros` SET `tipo_via` = 'CALLE', `tipo_via_id` = '20' WHERE (`id` = '113');
UPDATE `centros` SET `direccion` = 'MOLINO' WHERE (`id` = '116');
UPDATE `centros` SET `tipo_via` = 'CARRETERA', `tipo_via_id` = '27', `direccion` = 'VIEJA LOS SANTOS DE MAIMONA' WHERE (`id` = '117');
UPDATE `centros` SET `nombre` = 'RESIDENCIA ANCIANOS CORIA' WHERE (`id` = '119');
UPDATE `centros` SET `nombre` = 'RESIDENCIA CLUB ANCIANOS FUENTE DE CANTOS, RESIDENCIA NUESTRA SEÑORA DE GUADALUPE', `telefono` = '924500335' WHERE (`id` = '120');
UPDATE `centros` SET `tipo_via` = 'AVENIDA', `tipo_via_id` = '10' WHERE (`id` = '122');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE ANCIANOS SAN ANTONIO, RESIDENCIA SAN PEDRO DE ALCANTARA', `tipo_via` = 'AVENIDA', `tipo_via_id` = '10', `direccion` = 'DE LISBOA', `numero` = '2' WHERE (`id` = '126');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE MAYORES ANTONIO ZAPATA' WHERE (`id` = '128');
UPDATE `centros` SET `direccion` = 'LOS HUERTOS' WHERE (`id` = '129');
UPDATE `centros` SET `nombre` = 'RESIDENCIA DE MAYORES  DELEITOSA' WHERE (`id` = '135');
/*UPDATE `centros` SET `id` = '137' WHERE (`id` = '137');*/
UPDATE `centros` SET `tipo_via` = 'AVENIDA', `tipo_via_id` = '10' WHERE (`id` = '140');
UPDATE `centros` SET `tipo_via` = 'AVENIDA', `tipo_via_id` = '10' WHERE (`id` = '156');
UPDATE `centros` SET `direccion` = 'MADRID', `numero` = '103' WHERE (`id` = '159');
UPDATE `centros` SET `tipo_via` = 'CARRETERA', `direccion` = 'PORTUGAL', `numero` = '3' WHERE (`id` = '160');
UPDATE `centros` SET `tipo_via` = 'CALLE', `tipo_via_id` = '20', `direccion` = 'ROSO DE LUNA', `numero` = '2' WHERE (`id` = '161');
UPDATE `centros` SET `tipo_via` = 'TRAVESIA', `tipo_via_id` = '77', `direccion` = 'FLEMING' WHERE (`id` = '170');
UPDATE `centros` SET `tipo_via` = 'CARRETERA', `tipo_via_id` = '27', `direccion` = 'COMARCAL', `numero` = '511' WHERE (`id` = '172');
UPDATE `centros` SET `tipo_via` = 'CARRETERA', `tipo_via_id` = '27', `direccion` = 'CIRCUNVALACION' WHERE (`id` = '173');
UPDATE `centros` SET `tipo_via` = 'CALLE', `tipo_via_id` = '20', `direccion` = 'ZONA PERI-INDUSTRIAL', `numero` = '27A' WHERE (`id` = '191');
UPDATE `centros` SET `tipo_via` = 'AVENIDA', `tipo_via_id` = '10' WHERE (`id` = '196');
UPDATE `centros` SET `nombre` = 'ACIS ASOCIACION DE MUJERES MALTRATADAS CACERES' WHERE (`id` = '204');


