/*insercion de expedientes que tienen datos en base roja tras habernos descargado nosotros la tabla anteriormente. Insercion de datos en expedientes intranet, para relacionarlo con expedientes_datos_personales*/
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,
num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,
 expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values 
 ((select id from expediente_datos_personales where nombre='JOSE MIGUEL' and apellido1='CORDERO' and apellido2='MASA'),
 '75/2024','07/CR/2024',NULL,'2024-01-01','CURATELA REPRESENTATIVA',(select id from estados where nombre='ALTA'),'296/13','10195-41-1-2023-0000556',
 (select id from juzgados where nombre='1ª INSTANCIA Nº 2 DE TRUJILLO'),(select id from figuras where nombre='SENTENCIA'),'296','2013-11-01',
 (select id from juzgados where nombre='1ª INSTANCIA Nº 2 DE TRUJILLO'),(select id from figuras where nombre='AUTO'),'163','2024-11-29',
 (select id from juzgados where nombre='1ª INSTANCIA Nº 2 DE TRUJILLO'),'81','2009-04-16','2013-05-26','0','FALSO',(select id from grado_dependencias where grado=NULL),
 (select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-04-12','FALSO','07/CR/2024','07/CR/2024',
 'CURATELA REPRESENTATIVA','CURATELA REPRESENTATIVA',
 (select id from procedimientos_judiciales where abreviatura='X59'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values ((select id from expediente_datos_personales where nombre='JONATAN' and apellido1='GARCIA' and apellido2='TERRON'),'09/2024','02/CA/2024','2','2024-01-01','CURATELA ASISTENCIAL',(select id from estados where nombre='ALTA'),'1031/22','06015-42-1-2022-0009276',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='SENTENCIA'),'1031',NULL,(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='AUTO'),'103','2024-02-06',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),'65','2007-02-08','2007-02-08','0','FALSO',(select id from grado_dependencias where grado=NULL),(select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-08-01','FALSO','02/CA/2024','02/CA/2024','CURATELA ASISTENCIAL','CURATELA ASISTENCIAL',(select id from procedimientos_judiciales where abreviatura='X58'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values ((select id from expediente_datos_personales where nombre='ALEJANDRO' and apellido1='LOPEZ' and apellido2='GILARTE'),'62/2024','16/CR/2024',NULL,'2024-01-01','CURATELA',(select id from estados where nombre='ALTA'),'238/14','10148-41-1-2024-0000874',(select id from juzgados where nombre='1ª INSTANCIA Nº 5 DE PLASENCIA'),(select id from figuras where nombre='SENTENCIA'),'238',NULL,(select id from juzgados where nombre='1ª INSTANCIA Nº 5 DE PLASENCIA'),(select id from figuras where nombre='AUTO'),'186','2024-05-29',(select id from juzgados where nombre='1ª INSTANCIA Nº 5 DE PLASENCIA'),'60','2024-07-12','2019-07-12',NULL,'FALSO',(select id from grado_dependencias where grado=NULL),(select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-07-22','FALSO','16/CR/2024','16/CR/2024','CURATELA REPRESENTATIVA','CURATELA REPRESENTATIVA',(select id from procedimientos_judiciales where abreviatura='X58'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values ((select id from expediente_datos_personales where nombre='JUAN LUIS' and apellido1='LOZANO' and apellido2='ORDOÑEZ'),'3/2024','01/CR/2024','1','2024-01-01','CURATELA REPRESENTATIVA',(select id from estados where nombre='ALTA'),'647/22','06083-41-1-2002-0201448',(select id from juzgados where nombre='1ª INSTANCIA Nº 2 DE MERIDA'),(select id from figuras where nombre='SENTENCIA'),'93','2023-04-05',(select id from juzgados where nombre='1ª INSTANCIA Nº 2 DE MERIDA'),(select id from figuras where nombre='SENTENCIA'),'93','2023-04-25',(select id from juzgados where nombre='1ª INSTANCIA Nº 2 DE MERIDA'),'65','2006-06-29','2006-10-19','0','VERDADERO',(select id from grado_dependencias where grado='III'),(select id from nivel_dependencias where nivel='2'),'2009-02-25','2007-12-13','ATENCION RESIDENCIAL','RESIDENCIA APOYO EXTENSO:RAE-PARALISIS CEREBRAL','PRESTACION DE SERVICIO','2023-12-05','FALSO','01/T/2024','01/CR/2024','CURATELA REPRESENTATIVA','CURATELA REPRESENTATIVA',(select id from procedimientos_judiciales where abreviatura='DT5'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values ((select id from expediente_datos_personales where nombre='YOLANDA' and apellido1='MARTIN' and apellido2='VELASCO'),'86/2023','07/CA/2023','1','2023-01-01','CURATELA ASISTENCIAL',(select id from estados where nombre='ALTA'),'829/13','06015-42-1-2023-0007318',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='AUTO'),'527','2023-12-12',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='AUTO'),'527','2023-12-12',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),'65','2017-01-20','2018-04-04','0','FALSO',(select id from grado_dependencias where grado=NULL),(select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-03-27','FALSO','07/CA/2023','07/CA/2023','CURATELA ASISTENCIAL','CURATELA ASISTENCIAL',(select id from procedimientos_judiciales where abreviatura='X58'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values ((select id from expediente_datos_personales where nombre='MIGUEL ANGEL' and apellido1='MONROY' and apellidO2='FERNANDEZ'),'5/2024','09/CR/2024','3','2024-01-01','CURATELA REPRESENTATIVA',(select id from estados where nombre='ALTA'),'1106/2023','06015-42-1-2023-0009900',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='SENTENCIA'),'1106',NULL,(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='AUTO'),'63','2024-01-23',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),'65','1991-04-30','1996-09-25','0','FALSO',(select id from grado_dependencias where grado=NULL),(select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-07-10','FALSO','09/CR/2024','09/CR/2024','CURATELA REPERESENTATIVA','CURATELA REPRESENTATIVA',(select id from procedimientos_judiciales where abreviatura='X58'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values ((select id from expediente_datos_personales where nombre='ENCARNACION' and apellido1='PITEL' and apellido2='MARQUEZ'),'32/2024','11/CR/2024','1','2024-01-01','CURATELA REPRESENTATIVA',(select id from estados where nombre='ALTA'),'872/23','06015-42-1-20230007822',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='SENTENCIA'),'872',NULL,(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),(select id from figuras where nombre='AUTO'),'213','2024-04-09',(select id from juzgados where nombre='1ª INSTANCIA Nº 4 DE BADAJOZ'),NULL,NULL,NULL,NULL,'FALSO',(select id from grado_dependencias where grado=NULL),(select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-06-19','FALSO','11/CR/2024','11/CR/2024','CURATELA REPRESENTATIVA','CURATELA REPRESENTATIVA',(select id from procedimientos_judiciales where abreviatura='X58'));
INSERT INTO expedientes_intranet (expediente_datos_personales_id,num_expte_intranet,expte, trabajador_social_id,fecha_alta, regimen,estado_id,num_incapacidad,nig,juzgado_id,resolucion_icp,
num_resolucion_icp,fecha_dictado_icp,juzgado_dictado_icp,resolucion_nb,num_resolucion_nb,fecha_dictado_nb,juzgado_dictado_nb,grado_discapacidad,fecha_discapacidad,fecha_valor_discapacidad,revisable_definitiva,activo_dp,
 gradodependencia_id,niveldependencia_id,fecha_resolucion,fecha_efectos,servicio_dependencia,subtipo_servicio,prestacion_dependencia,fecha_aceptacion_cargo,presentacion_rdc,expte_antiguo,
 expte_antes_revison,regimen_actual,regimen_definitivo,procedimientojudicial_id )values 
 ((select id from expediente_datos_personales where nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'),
 '24/2024','08/CR/2024','2','2024-01-01','CURATELA REPRESENTATIVA',(select id from estados where nombre='ALTA'),NULL,'10148-41-1-2023-0003429',
 (select id from juzgados where nombre='1ª INSTANCIA Nº 5 DE PLASENCIA'),(select id from figuras where nombre=NULL),NULL,NULL,
 (select id from juzgados where nombre=NULL),(select id from figuras where nombre='AUTO'),'108','2024-04-08',
 (select id from juzgados where nombre='1ª INSTANCIA Nº 5 DE PLASENCIA'),'75','2015-10-26','2015-12-23','0','FALSO',(select id from grado_dependencias where grado='II'),
 (select id from nivel_dependencias where nivel=NULL),NULL,NULL,NULL,NULL,NULL,'2024-07-11','FALSO','08/CR/2024','08/CR/2024',
 'CURATELA REPRESENTATIVA','CURATELA REPRESENTATIVA',
 (select id from procedimientos_judiciales where abreviatura='DT5'));