/*insercion de expedientes que tiene datos en el historial y que estan en base roja, pues se han insertado despues de descarganos nosotros la tabla*/
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('JOSE MIGUEL' , 'CORDERO','MASA', (select id from sexos where nombre ='HOMBRE'),'06/10095802/43','76032480T',NULL,'1981-06-16','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('JONATAN' , 'GARCIA','TERRON', (select id from sexos where nombre ='HOMBRE'),NULL,'80098183Q','2030-10-14','1989-04-12','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('ALEJANDRO' , 'LOPEZ','GILARTE', (select id from sexos where nombre ='HOMBRE'),NULL,'05461779V',NULL,'2006-09-07','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('JUAN LUIS' , 'LOZANO','ORDOÑEZ', (select id from sexos where nombre ='HOMBRE'),'06/00475651/31','05693360G',NULL,'1957-08-28','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('YOLANDA' , 'MARTIN','VELASCO', (select id from sexos where nombre ='MUJER'),'43/00558573/20','39700517X',NULL,'1969-08-06','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('MIGUEL ANGEL' , 'MONROY','FERNANDEZ', (select id from sexos where nombre ='MUJER'),NULL,'80067816D',NULL,'1978-09-19','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )values ('ENCARNACION' , 'PITEL','MARQUEZ', (select id from sexos where nombre ='MUJER'),NULL,'08850962X',NULL,'1970-06-07','FALSO');
INSERT INTO expediente_datos_personales (nombre,apellido1,apellido2,sexo_id,seg_social,numero_documento,fecha_caducidad_documento, fecha_nacimiento,no_por_edad_decesos )
values ('GLORIA' , 'VERA','LLORENTE', (select id from sexos where nombre ='MUJER'),NULL,'44783897E',NULL,'1982-11-27','FALSO');
