UPDATE `representantes` SET `nombre` = 'JOSE EMILIO' WHERE (`id` = '12') and nombre= 'JOSE EMILIIO';

insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('1', (select id from representantes where nombre='DEMETRIO JESUS'and 'GALLARDO REDONDO'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='TIO SEGUNDO' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('2', (select id from representantes where nombre='COMITE CIUDADANO ANTISIDA DE BURGOS'), (select id from relaciones where nombre='OTROS' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('3', (select id from representantes where nombre='DIEGO'and 'MORENO GIL'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='OTROS' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('4', (select id from representantes where nombre='FUNDACION MALAGUEÑA DE TUTELAS'), (select id from relaciones where nombre='OTROS' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('5', (select id from representantes where nombre='ELADIA'and 'FERNANDEZ SANCHEZ'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='HERMANA' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('6', (select id from representantes where nombre='JUANA'and 'RODRIGUEZ GARCIA'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='PRIMA HERMANA' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('7', (select id from representantes where nombre='AGENCIA MADRILEÑA PARA LA TUTELA DE ADULTOS'), (select id from relaciones where nombre='INSTITUCION TUTELAR' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('8', (select id from representantes where nombre='MARIA DOLORES'and 'SANCHO RODRIGUEZ'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='HIJA' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('9', (select id from representantes where nombre='FRANCISCO'and 'ESCUDERO ALMENA'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='OTROS' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('10', (select id from representantes where nombre='FRANCISCO'and 'NIETO LABRADOR'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='HERMANO' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('10', (select id from representantes where nombre='TELESFORA'and 'NIETO LABRADOR'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='HERMANA' ));
insert into representantes_remocion(remocion_id, representante_id, relacion_id) values ('11', (select id from representantes where nombre='JOSE EMILIO'and 'PARRA DIAZ'=concat(apellido1,' ',apellido2)), (select id from relaciones where nombre='PADRE' ));
