UPDATE `provincias` SET `nombre` = 'ALBACETE' WHERE (`id` = '1');
UPDATE `provincias` SET `nombre` = 'ALICANTE' WHERE (`id` = '2');
UPDATE `provincias` SET `nombre` = 'ALMERIA' WHERE (`id` = '3');
UPDATE `provincias` SET `nombre` = 'ALAVA' WHERE (`id` = '4');
UPDATE `provincias` SET `nombre` = 'ASTURIAS' WHERE (`id` = '5');
UPDATE `provincias` SET `nombre` = 'AVILA' WHERE (`id` = '6');
UPDATE `provincias` SET `nombre` = 'BADAJOZ' WHERE (`id` = '7');
UPDATE `provincias` SET `nombre` = 'BALEARS,ILLES' WHERE (`id` = '8');
UPDATE `provincias` SET `nombre` = 'BARCELONA' WHERE (`id` = '9');
UPDATE `provincias` SET `nombre` = 'BIZKAIA' WHERE (`id` = '10');
UPDATE `provincias` SET `nombre` = 'BURGOS' WHERE (`id` = '11');
UPDATE `provincias` SET `nombre` = 'CACERES' WHERE (`id` = '12');
UPDATE `provincias` SET `nombre` = 'CADIZ' WHERE (`id` = '13');
UPDATE `provincias` SET `nombre` = 'CANTABRIA' WHERE (`id` = '14');
UPDATE `provincias` SET `nombre` = 'CASTELLON' WHERE (`id` = '15');
UPDATE `provincias` SET `nombre` = 'CIUDAD REAL' WHERE (`id` = '16');
UPDATE `provincias` SET `nombre` = 'CORDOBA' WHERE (`id` = '17');
UPDATE `provincias` SET `nombre` = 'CORUÑA, A' WHERE (`id` = '18');
UPDATE `provincias` SET `nombre` = 'CUENCA' WHERE (`id` = '19');
UPDATE `provincias` SET `nombre` = 'GIPUZCOA' WHERE (`id` = '20');
UPDATE `provincias` SET `nombre` = 'GIRONA' WHERE (`id` = '21');
UPDATE `provincias` SET `nombre` = 'GRANADA' WHERE (`id` = '22');
UPDATE `provincias` SET `nombre` = 'GUADALAJARA' WHERE (`id` = '23');
UPDATE `provincias` SET `nombre` = 'HUELVA' WHERE (`id` = '24');
UPDATE `provincias` SET `nombre` = 'JUESCA' WHERE (`id` = '25');
UPDATE `provincias` SET `nombre` = 'JAEN' WHERE (`id` = '26');
UPDATE `provincias` SET `nombre` = 'LEON' WHERE (`id` = '27');
UPDATE `provincias` SET `nombre` = 'LLEIDA' WHERE (`id` = '28');
UPDATE `provincias` SET `nombre` = 'LUGO' WHERE (`id` = '29');
UPDATE `provincias` SET `nombre` = 'MADRID' WHERE (`id` = '30');
UPDATE `provincias` SET `nombre` = 'MALAGA' WHERE (`id` = '31');
UPDATE `provincias` SET `nombre` = 'MURCIA' WHERE (`id` = '32');
UPDATE `provincias` SET `nombre` = 'NAVARRA' WHERE (`id` = '33');
UPDATE `provincias` SET `nombre` = 'OURENSE' WHERE (`id` = '34');
UPDATE `provincias` SET `nombre` = 'PALENCIA' WHERE (`id` = '35');
UPDATE `provincias` SET `nombre` = 'PALMAS, LAS' WHERE (`id` = '36');
UPDATE `provincias` SET `nombre` = 'PONTEVEDRA' WHERE (`id` = '37');
UPDATE `provincias` SET `nombre` = 'RIOJA, LA' WHERE (`id` = '38');
UPDATE `provincias` SET `nombre` = 'SALAMANCA' WHERE (`id` = '39');
UPDATE `provincias` SET `nombre` = 'SANTA CRUZ DE TENERIFE' WHERE (`id` = '40');
UPDATE `provincias` SET `nombre` = 'SEGOVIA' WHERE (`id` = '41');
UPDATE `provincias` SET `nombre` = 'SEVILLA' WHERE (`id` = '42');
UPDATE `provincias` SET `nombre` = 'SORIA' WHERE (`id` = '43');
UPDATE `provincias` SET `nombre` = 'TARRAGONA' WHERE (`id` = '44');
UPDATE `provincias` SET `nombre` = 'TERUEL' WHERE (`id` = '45');
UPDATE `provincias` SET `nombre` = 'TOLEDO' WHERE (`id` = '46');
UPDATE `provincias` SET `nombre` = 'VALENCIA' WHERE (`id` = '47');
UPDATE `provincias` SET `nombre` = 'VALLADOLID' WHERE (`id` = '48');
UPDATE `provincias` SET `nombre` = 'ZAMORA' WHERE (`id` = '49');
UPDATE `provincias` SET `nombre` = 'ZARAGOZA' WHERE (`id` = '50');
UPDATE `provincias` SET `nombre` = 'CEUTA' WHERE (`id` = '51');
UPDATE `provincias` SET `nombre` = 'MELILLA' WHERE (`id` = '52');
