
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ANGEL','PEREZ','ARIAS','ELJAS, 48','Ceclavin','10870',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARIA JOSE','PEREZ','GRANADOS',NULL,NULL,NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARCIANO','ALEGRE','COLAR','SANTA ANA, 22','Plasencia','10600',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JOSE ANTONIO','PULIDO','MERINO','C/ PIZARRO, 7','Montehermoso','10810','639394453');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('CRISTETA','CRISTETA','MERINO',NULL,NULL,NULL,'927675077');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('EDUVIGIS','FUENTES','TORNERO','PZA. PRINCIPE FELIPE, 2, 2º PTA. B','Aldeanueva de la Vera','10440',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('SONIA','GILARTE','FUENTES','PZA. PRINCIPE FELIPE, 2, 2º PTA. B','Aldeanueva de la Vera','10440',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MANUEL','CAMPOS','ARCE','CAMINO SANTA ENGRACIA, 91','Badajoz','06800',NULL);

INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('BONIFACIA','MARTIN','CRESPO',NULL,'Nuñomoral','10626',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('PEDRO','CRESPO','MARTIN',NULL,NULL,NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('EMILIA','SANTILLANA',NULL,NULL,'Caceres','10001','927225772');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('PILAR','PEREZ','GARCIA',NULL,NULL,NULL,'637290022');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('CARMEN','GATO','LOZANO','C/ FORTALEZA, 4, PTA. A, 1º H','Sevilla',NULL,'954279825');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('TERESA','TARANGO','DOMINGO',NULL,'Aldeanueva de la Vera','10440',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('CONCEPCION','DE LA MORENA','MARTINEZ','TRAVESIA DE LA FUENTE, 5, PORTAL 1, 1º IZDA.','Moralzarzal',NULL,'918578438');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ANTONIO','CAPILLA','IZQUIERDO','AVDA. DE LA CONSTITUCION, 83','Magacela','06498',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('FILOMENA','CAPITA','ARIAS','AVDA. DE LA CONSTITUCION, 83','Magacela','06498',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('AMELIA','SERRANO','TRANCON',NULL,'Aldeanueva de la Vera','10440','660946698');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JOSE','SERRANO','TRANCON',NULL,'Aldeanueva de la Vera','10440',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('LIDIA','MARTIN',NULL,NULL,'Palma de Mallorca',NULL,'971293984');

INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JULIA','MORA',NULL,NULL,'Coria','10800','927501925');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('PILAR','SERRANO','MOCHOLI','Calle Cruz de Piedra, 33','Coria','10800','927500246');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('INES','SERRANO','FERNANDEZ','CALLE LANCHO, 4, 1º A','Alcorcon',NULL,'916441320');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('URBANA','LORENZO','ROLDAN',NULL,NULL,'10600','927410575');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARIA DOLORES','PARIENTE','DOMINGUEZ','C/ Goya, 6-7º D','Cadiz',NULL,'956253055');


INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MERCEDES','CRESPO','PANADERO','C/ EMPECINADO, 8, 4 D',NULL,NULL,NULL);

INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('PLACIDA','GONZALEZ','CAMPOS',NULL,NULL,NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('CARLOTA','MEGIAS','FRUTOS',NULL,NULL,NULL,'914678478');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('EMILIO','MEGIAS','FRUTOS',NULL,'Valdemoro',NULL,'9180883592');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JOSE','ORGAZ','GALINDO','C/ MIGUEL MUÑOZ DAVILA, 5','Valdelacasa de Tajo','10332',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JUAN','BERMEJO','MATEOS',NULL,'Caceres','10001','927249330');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JUANA','BERMEJO','MATEOS',NULL,NULL,NULL,'914674819');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ELENA','GALLARDO','LOPEZ','VIA COMPLUTENSE, 73, 31 CENTRO','Madrid',NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JOSE','GALLARDO','LOPEZ',NULL,'Fregenal de la Sierra','06340',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JOSE','VEGA','DIAS','EL CORCHO, 44','Villanueva del Fresno','06110','924427107');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('CARMEN','LAZARO','MOSCATEL',NULL,NULL,NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('RAMONA','CANO','MARCHENA',NULL,NULL,NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ALBERTO','SANTOS','ZAPATA','ZABALA, 10','Fuente de Cantos','06240',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JACINTA','DAVILA','POZO',NULL,'Zalamea de la Serena','06430',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARIA LEONARDA','RODRIGUEZ','CALERO',NULL,'Donostia-San Sebastian','2001','943393633');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ENCARNACIÓN','RODRIGUEZ','CALERO','C/ TERESA DE CLARAMUNT, Nº 5','Guadalajara','19005','699982732');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARIA CARMEN','FERNANDEZ','PIÑAS',NULL,NULL,NULL,NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JUAN','BLANCO','MURILLO',NULL,'Campillo de Llerena','06443',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ELIAS ANGEL','FERNANDEZ','VEGA','C/ San Sebastián, nº 9','Torrejoncillo','10830','626230906');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('JUANA','RODRIGUEZ','GRAGERA','LUIS DE CAMOENS PARCELA 2','Merida','06800',NULL);
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ESTEFANIA','RODRIGUEZ','GRAGERA','GARCIA LORCA, 39','Calamonte','06810','924323531');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARIA CARMEN','ESCOBAR','MACIAS','TRAVESÍA SANTA MARÍA,6','Jerez de los Caballeros','06380','679833076');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('PILAR','DOMINGUEZ','JIMENEZ',NULL,'Barcarrota','06160','924736858');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('ANTONIO','DOMINGUEZ','JIMENEZ','VIENTO,39','Badajoz','06800','924242857');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('MARTIN','NEVADO','MAGRO','C/ PASEOS, 14','Salorino','10570','659005318');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('YOLANDA','VILLEGAS','SALGADO',NULL,'Badajoz','06004','634675798');
INSERT INTO representantes (nombre,apellido1,apellido2,domicilio,localidad,codigo_postal,telefono)values('SALUSTIANO',NULL,NULL,NULL,NULL,NULL,'619908873');

UPDATE representantes set domicilio=upper(domicilio);
UPDATE representantes set localidad=upper(localidad);
