update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='AVENIDA'),numero='39',planta='1',letra='D',direccion='DE ESPAÑA' where direccion='AVDA. DE ESPAÑA, 39, 1º D';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='AVENIDA'),numero='10',planta='4',letra='D',direccion='DE LA HISPANIDAD' where direccion='AVDA. DE LA HISPANIDAD, Nº 10, 4º D';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='PLAZA'),numero='2',planta='2',letra='B',direccion='PRINCIPE FELIPE' where direccion='PZA. PRINCIPE FELIPE, , Nº 2, PISO 2º B';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='',planta='',letra='',direccion='CALEROS' where direccion='C/ CALEROS, 27';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='16',planta='',letra='',direccion='SAN MARCOS' where direccion='SAN MARCOS, 16';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='21',planta='',letra='',direccion='ARRABAL' where direccion='C/ ARRABAL, 21';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='PLAZA'),numero='15',planta='',letra='',direccion='SAN ANTON' where direccion='PZA. SAN ANTON, 15';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='3',planta='6',letra='1D',direccion='RONDA DE LA PIZARRA' where direccion='C/ RONDA DE LA PIZARRA, 3, 6º 1-D';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='AVENIDA'),numero='43',planta='',letra='',direccion='DE EXTREMADURA' where direccion='AVDA. DE EXTREMADURA, 43';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='PLAZA'),numero='14',planta='',letra='',direccion='DE CASTELAR' where direccion='PZA. DE CASTELAR, 14';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='PLAZA'),numero='14',planta='',letra='',direccion='DE CASTELAR' where direccion='PZA. CASTELAR,14';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='30',planta='',letra='',direccion='REYES CATOLICOS' where direccion='REYES CATOLICOS, 30';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='1',planta='',letra='',direccion='TRUJILLO' where direccion='C/ TRUJILLO, Nº 1';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='16',planta='',letra='',direccion='CASILLAS' where direccion='C/ CASILLAS, 16';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='PASAJE'),numero='POLIGONO 41',planta='PARCELA 276',letra='',direccion='CERRILLO' where direccion='PARAJE CERRILLO POLIGONO 41 PARCELA 276';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='22',planta='',letra='',direccion='RISCO' where direccion='C/ RISCO, 22';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='46',planta='',letra='',direccion='SEXMO' where direccion='C/ SEXMO, 46';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='15',planta='',letra='',direccion='CALILLA' where direccion='C/ CALILLA, 15';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='61',planta='',letra='',direccion='MARQUES DE CASACAJIGAL' where direccion='Marqués de Casascajigal, 61';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='',planta='',letra='',direccion='CALDERON DE LA BARCA' where direccion='CALDERON DE LA BARCA';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='15',planta='',letra='',direccion='ZURBARAN' where direccion='ZURBARAN,15';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='17',planta='1',letra='A',direccion='NICOLAS LOPEZ DE VELASCO' where direccion='NICOLAS LOPEZ DE VELASCO 17 1 A';
update bienes_inmuebles set tipo_via_id=(select id from tipos_via where nombre='CALLE'),numero='S/N',planta='BAJO',letra='',direccion='NUESTRA SEÑORA DEL PERPETUO SOCORRO' where direccion='NUESTRA SEÑORA DEL PERPETUO SOCORRO SN BAJO';
