UPDATE `prestaciones` SET `nombre` = 'CLASES PASIVAS ORFANDAD FAMILIAR RETIRADOS' WHERE (`id` = '2') AND nombre='CLASES PASIVAS ORFANDAD FAM RETIRADOS';
UPDATE `prestaciones` SET `nombre` = 'PENSION NO CONTRIBUTIVA' WHERE (`id` = '27') AND nombre='PNC';
UPDATE `prestaciones` SET `nombre` = 'PENSION NO CONTRIBUTIVA INCAPACIDAD' WHERE (`id` = '28') AND nombre='PNC INCAPACIDAD';
UPDATE `prestaciones` SET `nombre` = 'PRESTACION ECONOMICA CUIDADOS ENTORNO FAMILIAR' WHERE (`id` = '29') AND nombre='PRESTACION ECCA. CUIDADOS ENTORNO FAMILIAR';
UPDATE `prestaciones` SET `nombre` = 'PRESTACION ECONOMICA VINCULADA AL SERVICIO' WHERE (`id` = '30') AND nombre='PRESTACION ECCA. VINCULADA AL SERVICIO';
UPDATE `prestaciones` SET `nombre` = 'SEGURO OBLIGATORIO DE VEJEZ E INVALIDEZ NO COMUN' WHERE (`id` = '36') AND nombre='VEJEZ SOVI NO COMUN';
UPDATE `prestaciones` SET `nombre` = 'FAVOR FAMILIARES CON % VIUDEDAD (LEY 26/85)' WHERE (`id` = '38') AND nombre='FAV. FAMILIARES CON % VIUDEDAD (LEY 26/85)';


