UPDATE `expediente_datos_personales` SET `apellido` = 'DOS SANTOS', `apellido2` = 'DOS SANTOS' WHERE (`id` = '54')  and numero_documento='X1818105R';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA MORENA', `apellido2` = 'MARTINEZ' WHERE (`id` = '86') and numero_documento='05251471L';
UPDATE `expediente_datos_personales` SET `apellido` = 'DA SILVA', `apellido2` = 'BAUTISTA' WHERE (`id` = '99') and numero_documento='07045093D';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA MORENA', `apellido2` = 'MARTINEZ' WHERE (`id` = '262') and numero_documento='00395175N';
UPDATE `expediente_datos_personales` SET `apellido` = 'DOS SANTOS', `apellido2` = 'DOS SANTOS' WHERE (`id` = '264') and numero_documento='11634360 5 ZX4';
UPDATE `expediente_datos_personales` SET `apellido` = 'DOS SANTOS', `apellido2` = 'DOS SANTOS' WHERE (`id` = '306') and numero_documento='X2924090P';
UPDATE `expediente_datos_personales` SET `apellido` = 'DA COSTA', `apellido2` = 'LORENZO' WHERE (`id` = '328') and numero_documento='80256008S';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA MORENA', `apellido2` = 'MARTINEZ' WHERE (`id` = '333') and numero_documento='05251472C';
UPDATE `expediente_datos_personales` SET `apellido` = 'DOS SANTOS', `apellido2` = 'DOS SANTOS' WHERE (`id` = '397') and numero_documento='X1818081T';
UPDATE `expediente_datos_personales` SET `apellido` = 'RIZEA' WHERE (`id` = '479') and numero_documento='Y-1090272-V';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA MORENA', `apellido2` = 'MARTINEZ' WHERE (`id` = '498') and numero_documento='00395176J';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA OSA', `apellido2` = 'DE LA OSA' WHERE (`id` = '499') and numero_documento='28949416Y';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA MORENA', `apellido2` = 'MARTINEZ' WHERE (`id` = '513') and numero_documento='00395177Z';
UPDATE `expediente_datos_personales` SET `apellido` = 'MEMET' WHERE (`id` = '604') and numero_documento='X09649378G';
UPDATE `expediente_datos_personales` SET `apellido` = 'EL KINTY', `apellido2` = 'SNEIBA' WHERE (`id` = '630') and numero_documento='Y3493960K';
UPDATE `expediente_datos_personales` SET `apellido` = 'DA CONCEIÇAO', `apellido2` = 'BEZERRA' WHERE (`id` = '661') and numero_documento='X3157069R';
UPDATE `expediente_datos_personales` SET `apellido` = 'DEL OLMO', `apellido2` = 'SANTIAGO' WHERE (`id` = '799') and apellido1='DEL OLMO SANTIAGO';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE LA CAMARA', `apellido2` = 'AYALA' WHERE (`id` = '805') and apellido1='DE LA CAMARA AYALA';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE SANDE', `apellido2` = 'CHAPARRO' WHERE (`id` = '881') and apellido1='DE SANDE CHAPARRO';
UPDATE `expediente_datos_personales` SET `apellido` = 'DEL AGUILA', `apellido2` = 'BLANCO' WHERE (`id` = '924') and apellido1='DEL AGUILA BLANCO';
UPDATE `expediente_datos_personales` SET `apellido` = 'DE PRADO', `apellido2` = 'CARRILLO' WHERE (`id` = '1239') and apellido1='DE PRADO CARRILLO';
UPDATE `expediente_datos_personales` SET `apellido` = 'RAMADAN' WHERE (`id` = '1272') and apellido1='RAMADAN';
UPDATE `expediente_datos_personales` SET `apellido` = 'NGUVULU' WHERE (`id` = '1276') and apellido1='NGUVULU';
UPDATE `expediente_datos_personales` SET `apellido` = 'GARCIA DE PRUNEDA', `apellido2`='TREVIJANO' WHERE (`id` = '733' && `apellido1` = 'GARCIA DE PRUNEDA TREVIJANO');
