INSERT INTO patologia_concreta(nombre) VALUES ('ABUSO COCAINA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ABUSO DEL ALCOHOL');
INSERT INTO patologia_concreta(nombre) VALUES ('ACCIDENTE CEREBRAL VASCULAR AGUDO ');
INSERT INTO patologia_concreta(nombre) VALUES ('AGITACION PSICOMOTRIZ');
INSERT INTO patologia_concreta(nombre) VALUES ('ALCOHOLISMO');
INSERT INTO patologia_concreta(nombre) VALUES ('ALCOHOLISMO CRONICO');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACION CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACION DE CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACION DE LA CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACION PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACION PSIQUICA');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACIONES COGNITIVAS');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACIONES CONDUCTUALES');
INSERT INTO patologia_concreta(nombre) VALUES ('ALTERACIONES DE CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('ALZHEIMER ');
INSERT INTO patologia_concreta(nombre) VALUES ('ALZHEIMER MODERADO GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('ALZHEIMER MODERADO SEVERO');
INSERT INTO patologia_concreta(nombre) VALUES ('AMPUTACION DEDOS');
INSERT INTO patologia_concreta(nombre) VALUES ('AMPUTACION SUPRACONDILEA PIERNA IZQUIERDA');
INSERT INTO patologia_concreta(nombre) VALUES ('ANEMIA CARENCIAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('ANEMIA MICROCRITICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ANOREXIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ANTECEDENTES EPILEPSIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ANTECEDENTES RETRASO MENTAL LIGERO');
INSERT INTO patologia_concreta(nombre) VALUES ('ARTROSIS RODILLA DERECHA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ASMA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ATAXIA DE FRIEDREICH');
INSERT INTO patologia_concreta(nombre) VALUES ('AUSENCIA CONTROL ESFERA SEXUA');
INSERT INTO patologia_concreta(nombre) VALUES ('AUTISMO');
INSERT INTO patologia_concreta(nombre) VALUES ('BIPOLARIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('BIPOLARIDAD LARGA EVOLUCION ');
INSERT INTO patologia_concreta(nombre) VALUES ('BIPOLARIDAD TIPO I ');
INSERT INTO patologia_concreta(nombre) VALUES ('BRADIPSIQUIA');
INSERT INTO patologia_concreta(nombre) VALUES ('BRONQUITIS CRONICA');
INSERT INTO patologia_concreta(nombre) VALUES ('BROTES PSICOTICOS ');
INSERT INTO patologia_concreta(nombre) VALUES ('C.I. LIMITE ');
INSERT INTO patologia_concreta(nombre) VALUES ('CAPACIDAD INTELECTUAL LIMITE ');
INSERT INTO patologia_concreta(nombre) VALUES ('CAPSULITIS ADHESIVA HOMBRO DERECHO');
INSERT INTO patologia_concreta(nombre) VALUES ('CAQUEXIA');
INSERT INTO patologia_concreta(nombre) VALUES ('CARCINOMA');
INSERT INTO patologia_concreta(nombre) VALUES ('CARDIOPATIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('CATARA OJO DERECHO ');
INSERT INTO patologia_concreta(nombre) VALUES ('CEGUERA ');
INSERT INTO patologia_concreta(nombre) VALUES ('CIRROSIS HEPATICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('COEFICIENTE INTELECTUAL LIMITE');
INSERT INTO patologia_concreta(nombre) VALUES ('CONSUMO CANNABIS ');
INSERT INTO patologia_concreta(nombre) VALUES ('COREA HUNTINGTON ');
INSERT INTO patologia_concreta(nombre) VALUES ('CRISIS COMICIALES');
INSERT INTO patologia_concreta(nombre) VALUES ('DEBILIDAD MENTAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEBILIDAD MENTAL GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('DEBILIDAD MENTAL LEVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEBILIDAD MENTAL LEVE-MODERADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEBILIDAD MENTAL MEDIA');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIENCIA INTELECTUAL LEVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIENCIA INTELECTUAL PERINATAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT ATENCION ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT AUDITIVO LEVE-MODERADO');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT INTELECTUAL GRAVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT INTELECTUAL LIGERO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT INTELECTUAL MODERADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT VISUAL');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT VISUAL BILATERAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEFICIT VISUAL MODERADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DELECION CROMOSOMA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DELIRIOS');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA ALCOHOLICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA AVANZADA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA CON LESION ESTRUCTURAL CEREBRAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA GRAVE ORIGEN MIXTO, VASCULAR Y DEGENARATIVO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA MODERADA');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA SENIL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA VASCULAR');
INSERT INTO patologia_concreta(nombre) VALUES ('DEMENCIA WERNICKE-KORSAKOF');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPENDENCIA ALCOHOL');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPENDENCIA ALCOHOLICA');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPENDENCIA ALCOHOLICA CRONICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPENDENCIA CANNABIS');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPENDENCIA DROGAS ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPENDENCIA SUSTANCIAS PSICOACTIVAS ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPRESION');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPRESION CRONICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DEPRESION MAYOR RECURRENTE');
INSERT INTO patologia_concreta(nombre) VALUES ('DESCONTROL IMPULSOS');
INSERT INTO patologia_concreta(nombre) VALUES ('DESORGANIZACION CONDUCTUAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO CAPACIDAD JUICIO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO GRAVE - DEMENCIA EVOLUCIONADA TIPO ALZHEIMER');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO LEVE');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO LEVE-MODERADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO MODERADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO MODERADO-GRAVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO MUY GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO SEVERO ');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO COGNITIVO VASCULAR');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO MOTOR');
INSERT INTO patologia_concreta(nombre) VALUES ('DETERIORO PSIQUICO Y FISICO GENERAL');
INSERT INTO patologia_concreta(nombre) VALUES ('DIABETES');
INSERT INTO patologia_concreta(nombre) VALUES ('DIABETES MELLITUS');
INSERT INTO patologia_concreta(nombre) VALUES ('DIABETES MELLITUS TIPO II');
INSERT INTO patologia_concreta(nombre) VALUES ('DIABETES TIPO I ');
INSERT INTO patologia_concreta(nombre) VALUES ('DIABETES TIPO II ');
INSERT INTO patologia_concreta(nombre) VALUES ('DIFICIL DEAMBULACION');
INSERT INTO patologia_concreta(nombre) VALUES ('DIOGENES');
INSERT INTO patologia_concreta(nombre) VALUES ('DIPLEJIA ESPASTICA LEVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISC. SIST. OSTEOARTICULAR');
INSERT INTO patologia_concreta(nombre) VALUES ('DISC. SISTEMA OSTEOARTICULAR ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD FISICA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTECTUAL LIMITE');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTIVA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL 65% ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL GRAVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL GRAVE ASOCIADA A ALTERACION GENETICA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL LEVE');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL MODERADA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD INTELECTUAL MODERADO-SEVERO');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD MENTAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISCAPACIDAD PSIQUICA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISFASIA PRIMARIA PROGRESIVA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DISFEMIA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISLALIA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISLIPEMIA');
INSERT INTO patologia_concreta(nombre) VALUES ('DISTIMIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('DLP ');
INSERT INTO patologia_concreta(nombre) VALUES ('DROGODEPENDENCIA');
INSERT INTO patologia_concreta(nombre) VALUES ('ENCEFALOPATIA');
INSERT INTO patologia_concreta(nombre) VALUES ('ENCEFALOPATIA CONNATAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENCEFALOPATIA HIPOXICA PERINATAL CON DEFICIENCIA MODERADA PSICO-FISICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENDOTROPIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENF. ESOFAGO ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENF. HEPATICA CRONICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENF. VASCULAR PERIFERICA');
INSERT INTO patologia_concreta(nombre) VALUES ('ENFERMEDAD APARATO CIRCULATORIO ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENFERMEDAD APARATO DIGESTIVO ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENFERMEDAD APARATO RESPIRATORIO ');
INSERT INTO patologia_concreta(nombre) VALUES ('ENFERMEDAD FISICA');
INSERT INTO patologia_concreta(nombre) VALUES ('ENFERMEDAD MENTAL');
INSERT INTO patologia_concreta(nombre) VALUES ('ENFERMEDAD PSICOSOMATICA');
INSERT INTO patologia_concreta(nombre) VALUES ('EPILEPSIA');
INSERT INTO patologia_concreta(nombre) VALUES ('EPISODIOS DEPRESIVOS');
INSERT INTO patologia_concreta(nombre) VALUES ('EPISODIOS PSICOTICOS');
INSERT INTO patologia_concreta(nombre) VALUES ('EPOC ');
INSERT INTO patologia_concreta(nombre) VALUES ('ESCOLIOSIS ');
INSERT INTO patologia_concreta(nombre) VALUES ('ESCOLISIS');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA DELIRANTE');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA DESORGANIZADA');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA HEBEFRENICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA INDIFERENCIADA ');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA INDIFERENCIADA Y RESIDUAL');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA PARANOIDE');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA PARANOIDE CRONICA');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA PARANOIDE RESIDUAL');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA PARANOIDE RESIDUAL CRONICA');
INSERT INTO patologia_concreta(nombre) VALUES ('ESQUIZOFRENIA RESIDUAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('ESTEATOSIS HEPATICA');
INSERT INTO patologia_concreta(nombre) VALUES ('ETILISMO CRONICO');
INSERT INTO patologia_concreta(nombre) VALUES ('FIBRILACION AURICULAR ');
INSERT INTO patologia_concreta(nombre) VALUES ('FIBROMIALGIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('FIBROSIS PULMONAR ');
INSERT INTO patologia_concreta(nombre) VALUES ('FOBIA SOCIAL');
INSERT INTO patologia_concreta(nombre) VALUES ('FRACTURA DE CADERA NO INTERVENIDA');
INSERT INTO patologia_concreta(nombre) VALUES ('FRACTURA FEMUR INTERVENIDA');
INSERT INTO patologia_concreta(nombre) VALUES ('GESTOS AUTOLITICOS ');
INSERT INTO patologia_concreta(nombre) VALUES ('GLAUCOMA BILATERAL');
INSERT INTO patologia_concreta(nombre) VALUES ('HEMATOMA TALAMICO CEREBRAL DERECHO');
INSERT INTO patologia_concreta(nombre) VALUES ('HEMIPARESIA DCHA');
INSERT INTO patologia_concreta(nombre) VALUES ('HEMIPARESIA DERECHA');
INSERT INTO patologia_concreta(nombre) VALUES ('HEMIPARESIA IZQ. ');
INSERT INTO patologia_concreta(nombre) VALUES ('HEMIPAREXIA DCHA.');
INSERT INTO patologia_concreta(nombre) VALUES ('HEMIPAREXIA DERECHA');
INSERT INTO patologia_concreta(nombre) VALUES ('HEPATITIS CRONICA');
INSERT INTO patologia_concreta(nombre) VALUES ('HEPATOPATIA ALCOHOLICA');
INSERT INTO patologia_concreta(nombre) VALUES ('HERNIA HIATO ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERACTIVIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERLIPIDEMIA MIXTA');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERMETROPIA');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERTENSION');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERTENSION ESENCIAL');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERTESION ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPERTIROIDISMO ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPOACUSIA');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPOACUSIA BILATERAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPOACUSIA MEDIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPOACUSIA OIDO DCHO ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPOACUSIA SEVERA ');
INSERT INTO patologia_concreta(nombre) VALUES ('HIPOTIROIDISMO ');
INSERT INTO patologia_concreta(nombre) VALUES ('HISTRIONISMO ');
INSERT INTO patologia_concreta(nombre) VALUES ('ICTUS');
INSERT INTO patologia_concreta(nombre) VALUES ('ICTUS ISQUEMICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('IDEAS DELIRANTES');
INSERT INTO patologia_concreta(nombre) VALUES ('IMPULSIVIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('INCAPACIDAD DEAMBULAR ');
INSERT INTO patologia_concreta(nombre) VALUES ('INCONTINENCIA BIESFINTERINA');
INSERT INTO patologia_concreta(nombre) VALUES ('INCONTINENCIA URINARIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('INFUENCIABLE');
INSERT INTO patologia_concreta(nombre) VALUES ('INTELIGENCIA LIMITE');
INSERT INTO patologia_concreta(nombre) VALUES ('LABILIDAD AFECTIVA');
INSERT INTO patologia_concreta(nombre) VALUES ('LIM. FUNC. COLUMNA');
INSERT INTO patologia_concreta(nombre) VALUES ('LIM. FUNCIONAL COLUMNA ');
INSERT INTO patologia_concreta(nombre) VALUES ('LIMITACION FUNCIONAL DE COLUMNA');
INSERT INTO patologia_concreta(nombre) VALUES ('LIMITACION FUNCIONAL MIEMBRO INF.');
INSERT INTO patologia_concreta(nombre) VALUES ('LIMITACION FUNCIONAL MSD');
INSERT INTO patologia_concreta(nombre) VALUES ('LIMITACIONES FUNCIONALES ARTICULARES');
INSERT INTO patologia_concreta(nombre) VALUES ('LUDOPATIA');
INSERT INTO patologia_concreta(nombre) VALUES ('LUXACION CONGENITA CADERA IZQ.');
INSERT INTO patologia_concreta(nombre) VALUES ('MIOPIA');
INSERT INTO patologia_concreta(nombre) VALUES ('MIOPIA SEVERA');
INSERT INTO patologia_concreta(nombre) VALUES ('MUDEZ');
INSERT INTO patologia_concreta(nombre) VALUES ('NEFROLITIASIS ');
INSERT INTO patologia_concreta(nombre) VALUES ('NEUROFIBROMATOSIS ');
INSERT INTO patologia_concreta(nombre) VALUES ('NIVEL COGNITIVO BAJO');
INSERT INTO patologia_concreta(nombre) VALUES ('nombre');
INSERT INTO patologia_concreta(nombre) VALUES ('OBESIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGOFRENIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGOFRENIA CONGENITA');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGOFRENIA MEDIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGOFRENIA MODERADA ');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGOFRENIA PROFUNDA');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGROFENIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('OLIGROFRENIA');
INSERT INTO patologia_concreta(nombre) VALUES ('ORTOFORIA');
INSERT INTO patologia_concreta(nombre) VALUES ('OSTEOARTROSIS');
INSERT INTO patologia_concreta(nombre) VALUES ('OSTEOPOROSIS ');
INSERT INTO patologia_concreta(nombre) VALUES ('PARALISIS CEREBRAL');
INSERT INTO patologia_concreta(nombre) VALUES ('PARALISIS CEREBRAL CON RETRASO PSICOMOTOR');
INSERT INTO patologia_concreta(nombre) VALUES ('PARALISIS CEREBRAL INFANTIL ');
INSERT INTO patologia_concreta(nombre) VALUES ('PARALISIS CEREBRAL MIXTA');
INSERT INTO patologia_concreta(nombre) VALUES ('PARANOIA');
INSERT INTO patologia_concreta(nombre) VALUES ('PARAPARESIA ESPASTICA');
INSERT INTO patologia_concreta(nombre) VALUES ('PAREXIA NERVIO PERIFERICO');
INSERT INTO patologia_concreta(nombre) VALUES ('PARKINSON');
INSERT INTO patologia_concreta(nombre) VALUES ('PARKINSON A FARMACOS ');
INSERT INTO patologia_concreta(nombre) VALUES ('PATOLOGIA MANIFORME');
INSERT INTO patologia_concreta(nombre) VALUES ('PATOLOGIAS PROPIAS DE LA EDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('PERDIDA AGUDEZA VISUAL');
INSERT INTO patologia_concreta(nombre) VALUES ('PERDIDA AGUDEZA VISUAL LEVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('PERDIDA ORGANO GENITOURINARIO ');
INSERT INTO patologia_concreta(nombre) VALUES ('PERDIDA VISION ');
INSERT INTO patologia_concreta(nombre) VALUES ('PERSONALIDAD CLUSTER B (HISTRIONISMO) ');
INSERT INTO patologia_concreta(nombre) VALUES ('PIE DEFORME');
INSERT INTO patologia_concreta(nombre) VALUES ('POLIDEPENDENCIA  SUSTANCIAS PSICOACTIVAS');
INSERT INTO patologia_concreta(nombre) VALUES ('POLINEUROPATIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('POLITOXICOMANIA');
INSERT INTO patologia_concreta(nombre) VALUES ('POSIBLE DEMENCIA');
INSERT INTO patologia_concreta(nombre) VALUES ('PROBLEMAS MOVILIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('PROBLEMAS OFTALMOLOGICOS');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS ');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS ATIPICA');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS DELIRANTE ');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS ESQUIZOFRENICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS HEBEFRÉNICA');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS PARANOIDE');
INSERT INTO patologia_concreta(nombre) VALUES ('PSICOSIS PARANOIDE DELIRANTE ');
INSERT INTO patologia_concreta(nombre) VALUES ('RASGOS AUTISMO ');
INSERT INTO patologia_concreta(nombre) VALUES ('RASGOS CLUSTER A Y B ');
INSERT INTO patologia_concreta(nombre) VALUES ('RASGOS DE PERSONALIDAD CLUSTER TIPO B ');
INSERT INTO patologia_concreta(nombre) VALUES ('RASGOS LIMITES PERSONALIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('RASGOS PERSONALIDAD ESQUIZOTIPICA HISTRIONICA Y LIMITE');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRAS MENTAL GRAVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MADURATIVO ');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL CON COEFICIENTE INTELECTUAL LIMITADO');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL LEVE ');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL LEVE-MODERADO');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL LIGERO ');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL MODERADO');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL MODERADO-GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO MENTAL MODERANO ');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO PROFUNDO');
INSERT INTO patologia_concreta(nombre) VALUES ('RETRASO PSICOMOTOR ');
INSERT INTO patologia_concreta(nombre) VALUES ('SECUELAS ICTUS ISQUEMICOS');
INSERT INTO patologia_concreta(nombre) VALUES ('SECUELAS NEUROLOGICAS ACVA');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDORME ANSIOSO-DEPRESIVO ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME ANSIOSO-DEPRESIVO ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME ANTICOLINERGICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME CONFUSIONAL AGUDO ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME CONNATAL-CONGENITO ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME DE DOWN');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME DEMENCIAL MODERADO-GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME DEPRESIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME DEPRESIVO MAYOR CRONICO CON SINTOMAS PSICOTICOS ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME DIOGENES');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME DOWN');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME INCOORDINACION ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME PREFONTRAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINDROME STURGE WEBER ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINTOMAS DEPRESIVOS ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINTOMAS PSICOTICOS');
INSERT INTO patologia_concreta(nombre) VALUES ('SINTOMAS RESIDUALES ');
INSERT INTO patologia_concreta(nombre) VALUES ('SINTOMATOLOGIA DEPRESIVA ');
INSERT INTO patologia_concreta(nombre) VALUES ('SODERA ');
INSERT INTO patologia_concreta(nombre) VALUES ('SORDERA ');
INSERT INTO patologia_concreta(nombre) VALUES ('SORDERA BILATERAL');
INSERT INTO patologia_concreta(nombre) VALUES ('SORDERA MEDIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('SORDOMUDEZ');
INSERT INTO patologia_concreta(nombre) VALUES ('SUGESTIONABLE ');
INSERT INTO patologia_concreta(nombre) VALUES ('TDAH');
INSERT INTO patologia_concreta(nombre) VALUES ('TDHA');
INSERT INTO patologia_concreta(nombre) VALUES ('TETRAPARESIA');
INSERT INTO patologia_concreta(nombre) VALUES ('TETRAPARESIA ESPASTICA ');
INSERT INTO patologia_concreta(nombre) VALUES ('TETRAPLEJIA ESPASTICA');
INSERT INTO patologia_concreta(nombre) VALUES ('TOXICOMANIA');
INSERT INTO patologia_concreta(nombre) VALUES ('TOXICOMANO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRANSTORNO CONDUCTA ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRANSTORNO MENTAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRANSTORNO MIXTO PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRANSTORNO PSICOTICO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRANSTORNOS DEL DESARROLLO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ADAPTATIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ADAPTATIVO CRONICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ADAPTATIVO MIXTO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO AFECTIVIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO AFECTIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO AGRESIVIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ANSIEDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ANSIOSO DEPRESIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ANSIOSO EVITATIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ANTISOCIAL PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO APARATO GENITO-URINARIO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO BIPOLAR ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO BIPOLAR TIPO I');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO COGNITIVO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO COMPORTAMIENTO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONDUCTA SEVERO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONDUCTUAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONSUMO CANNABIS');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONSUMO SUSTANCIAS');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONTROL IMPULSO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO CONTROL IMPULSOS');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE ANGUSTIA CON AGORAFOBIA ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE DEPRESION MAYOR');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE LA AFECTIVIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE LA CORNEA ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE LA MEMORIA');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE LA PERSONALIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE LA PERSONALIDAD LIMITE HISTRIONICO Y DEPENDIENTE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE LA PERSONALIDAD LIMITE Y ANTISOCIAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DE PERSONALIDAD GRUPO B CON RASGOS HISTRINICOS');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DEFICIT ATENCION ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DEFICIT ATENCION E HIPERACTIVIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DELIRANTE ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DELIRANTE CRONICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DELIRANTE GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DELIRANTE PARANOIDE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DELIRANTE PERSECUTORIO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DEPRESIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DEPRESIVO MAYOR RECIDIVANTE ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DEPRESIVO RECURRENTE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DESARROLLO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DISCO INTERVERTEBRAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DISOCIAL');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DISOCIAL PERSONALIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO DISTIMICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO EQUILIBRIO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ESPECTRO AUTISTA ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ESQUIZOAFECTIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ESQUIZOAFECTIVO TIPO BIPOLAR');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ESQUIZOIDE ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO ESTADO ANIMO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO GRAVE DE LA CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO HIGADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO HIPOCONDRIACO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO HISTRIONICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO HISTRIONICO PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO LIMITE PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO MENTAL');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO MENTAL LEVE-MODERADO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO MIXTO PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO MIXTO PERSONALIDAD GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO MUSCULO-ESQUELETICO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO NEGATIVISTA ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO NEUROCOGNITIVO MAYOR POR TRAUMATISMO CRANEOENCEFALICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO NEURODESARROLLO TIPO DAMP ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO OBSESIVO COMPULSIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO OBSESIVO COMPULSIVO GRAVE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO OFTALMOLOGICO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PARANOIDE');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PERSONALIDAD');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PERSONALIDAD CON RASGOS PARANOIDE Y ESQUIZOIDE ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PERSONALIDAD HISTRIONICO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PERSONALIDAD NO ESPECIFICADO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PSICOPATICO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PSICOTICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PSICOTICO AFILIAR ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PSICOTICO COMPARTIDO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO PSICOTICO NO FILIADO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO RESPIRACION ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO SISTEMA ENDOCRINO-METABOLICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO SOCIOPATICO PERSONALIDAD ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNO USO DE SUSTANCIAS ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNOS DE CONDUCTA');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTORNOS DIGESTIVOS ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTRONO AFECTIVO');
INSERT INTO patologia_concreta(nombre) VALUES ('TRASTRONO PSICOTICO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRATORNO SOMATOMORFO ');
INSERT INTO patologia_concreta(nombre) VALUES ('TRAUMATISMO CRANEOENCEFALICO');
INSERT INTO patologia_concreta(nombre) VALUES ('TUMOR CEREBRAL ');
INSERT INTO patologia_concreta(nombre) VALUES ('URTICARIA ');
