UPDATE centros SET codigo_postal='';

TRUNCATE table unidades_poblacionales_codigos_postales;
TRUNCATE table codigos_postales;
TRUNCATE table unidades_poblacionales;
TRUNCATE table municipios;
TRUNCATE table provincias;

INSERT INTO provincias(codigo,nombre) VALUES ('02',"Albacete");
INSERT INTO provincias(codigo,nombre) VALUES ('03',"Alicante/Alacant");
INSERT INTO provincias(codigo,nombre) VALUES ('04',"Almería");
INSERT INTO provincias(codigo,nombre) VALUES ('01',"Araba/Álava");
INSERT INTO provincias(codigo,nombre) VALUES ('33',"Asturias");
INSERT INTO provincias(codigo,nombre) VALUES ('05',"Ávila");
INSERT INTO provincias(codigo,nombre) VALUES ('06',"Badajoz");
INSERT INTO provincias(codigo,nombre) VALUES ('07',"Balears, Illes");
INSERT INTO provincias(codigo,nombre) VALUES ('08',"Barcelona");
INSERT INTO provincias(codigo,nombre) VALUES ('48',"Bizkaia");
INSERT INTO provincias(codigo,nombre) VALUES ('09',"Burgos");
INSERT INTO provincias(codigo,nombre) VALUES ('10',"Cáceres");
INSERT INTO provincias(codigo,nombre) VALUES ('11',"Cádiz");
INSERT INTO provincias(codigo,nombre) VALUES ('39',"Cantabria");
INSERT INTO provincias(codigo,nombre) VALUES ('12',"Castellón/Castelló");
INSERT INTO provincias(codigo,nombre) VALUES ('13',"Ciudad Real");
INSERT INTO provincias(codigo,nombre) VALUES ('14',"Córdoba");
INSERT INTO provincias(codigo,nombre) VALUES ('15',"Coruña, A");
INSERT INTO provincias(codigo,nombre) VALUES ('16',"Cuenca");
INSERT INTO provincias(codigo,nombre) VALUES ('20',"Gipuzkoa");
INSERT INTO provincias(codigo,nombre) VALUES ('17',"Girona");
INSERT INTO provincias(codigo,nombre) VALUES ('18',"Granada");
INSERT INTO provincias(codigo,nombre) VALUES ('19',"Guadalajara");
INSERT INTO provincias(codigo,nombre) VALUES ('21',"Huelva");
INSERT INTO provincias(codigo,nombre) VALUES ('22',"Huesca");
INSERT INTO provincias(codigo,nombre) VALUES ('23',"Jaén");
INSERT INTO provincias(codigo,nombre) VALUES ('24',"León");
INSERT INTO provincias(codigo,nombre) VALUES ('25',"Lleida");
INSERT INTO provincias(codigo,nombre) VALUES ('27',"Lugo");
INSERT INTO provincias(codigo,nombre) VALUES ('28',"Madrid");
INSERT INTO provincias(codigo,nombre) VALUES ('29',"Málaga");
INSERT INTO provincias(codigo,nombre) VALUES ('30',"Murcia");
INSERT INTO provincias(codigo,nombre) VALUES ('31',"Navarra");
INSERT INTO provincias(codigo,nombre) VALUES ('32',"Ourense");
INSERT INTO provincias(codigo,nombre) VALUES ('34',"Palencia");
INSERT INTO provincias(codigo,nombre) VALUES ('35',"Palmas, Las");
INSERT INTO provincias(codigo,nombre) VALUES ('36',"Pontevedra");
INSERT INTO provincias(codigo,nombre) VALUES ('26',"Rioja, La");
INSERT INTO provincias(codigo,nombre) VALUES ('37',"Salamanca");
INSERT INTO provincias(codigo,nombre) VALUES ('38',"Santa Cruz de Tenerife");
INSERT INTO provincias(codigo,nombre) VALUES ('40',"Segovia");
INSERT INTO provincias(codigo,nombre) VALUES ('41',"Sevilla");
INSERT INTO provincias(codigo,nombre) VALUES ('42',"Soria");
INSERT INTO provincias(codigo,nombre) VALUES ('43',"Tarragona");
INSERT INTO provincias(codigo,nombre) VALUES ('44',"Teruel");
INSERT INTO provincias(codigo,nombre) VALUES ('45',"Toledo");
INSERT INTO provincias(codigo,nombre) VALUES ('46',"Valencia/València");
INSERT INTO provincias(codigo,nombre) VALUES ('47',"Valladolid");
INSERT INTO provincias(codigo,nombre) VALUES ('49',"Zamora");
INSERT INTO provincias(codigo,nombre) VALUES ('50',"Zaragoza");
INSERT INTO provincias(codigo,nombre) VALUES ('51',"Ceuta");
INSERT INTO provincias(codigo,nombre) VALUES ('52',"Melilla");
