UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'AGESMER SL' WHERE (`id` = '1');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'SEGUROS ATOCHA' WHERE (`id` = '4');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'DKV ' WHERE (`id` = '7');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'NORTEHISPANA SEGUROS ' WHERE (`id` = '16');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'SEGUROS OCASO' WHERE (`id` = '17');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'PREVENTIVA SEGUROS' WHERE (`id` = '18');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'PURISIMA SEGUROS' WHERE (`id` = '19');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'SANTALUCIA' WHERE (`id` = '20');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'FUNERARIA ELIAS LOPEZ' WHERE (`id` = '8');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'ALIANZA ESPAÑOLA DE SEGUROS' WHERE (`id` = '2');
UPDATE `ctaex`.`aseguradoras` SET `nombre` = 'MAPFRE ' WHERE (`id` = '14');
