INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (406, 'VER MOVIMIENTOS BANCARIOS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (690, 'TRIMESTRAL');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (28, 'TOMADORA SU HERMANA MARIA TRINIDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (388, 'TOMADORA SU HERMANA MARIA TRINIDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (86, 'TODOS LOS HERMANOS INCLUIDOS EN ESTE SEGURO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (262, 'TODOS LOS HERMANOS INCLUIDOS EN ESTE SEGURO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (333, 'TODOS LOS HERMANOS INCLUIDOS EN ESTE SEGURO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (498, 'TODOS LOS HERMANOS INCLUIDOS EN ESTE SEGURO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (513, 'TODOS LOS HERMANOS INCLUIDOS EN ESTE SEGURO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (183, 'todos los años paga un suplemento para cubrir el gasto de un nicho.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (447, 'TODA LA PENSION LA RECOGEN LAS HERMANITAS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (520, 'TIENE SEGURO FAMILIAR CON NORTEHISPANA.22-5-2023.ÉSTE SEGURO ESTÁ DADO DE BAJA DESDE 2019. 24-5-2023.SE FORMALIZA SEGURO CON GENERALI.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (667, 'TIENE SEGURO DE HOGAR CON NORTEHISPANA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (102, 'TIENE SEGURO CON SU MADRE///PEDIDO CARTA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (507, 'TIENE PÓLIZA JUNTO CON SU MADRE(TUTELADA TAMBIÉN).');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (167, 'TIENE POLIZA CON SU TIO. LA COMPAÑÍA ES NORTEHISPANA, EL NÚMERO DE POLIZA ES 8176990-7 NO TENEMOS DOCUMENTACION.recibida 12-7-2022.está al corriente.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (43, 'tiene otro seguro con generali, dado de baja el 11-1-22.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (194, 'TIENE NICHO EN PROPIEDAD JUNTO CON PADRES EN AZUAGA. EL TITULO LO TIENE SU PRIMA PEPITA................924890120  SOBRINA CARMELITA... 610298434 Las dos viven en AZUAGA (Badajoz)  y prima MERCEDES CARRIZOSA  de Madrid T.: 626466213 y 917726385');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (417, 'TIENE NICHO EN MALPARTIDA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (83, 'TIENE DINERO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (421, 'tiene 71 mil € a 17-6-2022.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (634, 'TIENE  DINERO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (580, 'TENIA MAPFRE QUE POR ERROR SE LO HA ESTADO PAGANDO EL TUTELADO JOSE FERMIN GARCÍA PABLOS DESDE NOVIEMBRE 2016. dado de baja. LE QUEDO OCASO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (132, 'TAMBIEN TIENE SEGURO DE  VIVIENDA CON CASER');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (389, 'SU HIJO ESTÁ INCLUIDO EN LA PÓLIZA, TUTELADO TAMBIÉN.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (14, 'SOLO EN  PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (142, 'SOLICITADA POLIZA A marisol@diezchao.com.RECIBIDA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (600, 'SOLICITADA COPIA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (15, 'SIN SEGURO - SIN SALDO DE MOMENTO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (494, 'SIN SALDO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (385, 'SIN RECURSOS///NO TIENE CUENTA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (617, 'SEGURO QUE PAGABA EL HIJO Y LO QUITAMOS DE LA POLIZA , DOMICILIAMOS EN CUENTA DE TUTELADA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (206, 'SEGURO FAMILIAR');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (80, 'SEGURO CONTRATADO EL 1-8-2022');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (99, 'SEGURO CON SU PADRE, JUAN DA SILVA MARQUEZ, LO PAGAN DESDE LA CUENTA DE CATALINA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (343, 'SEGURO CON LA FAMILIA (HERMANA)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (70, 'SEGURO CON FAMILIA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (276, 'SEGURO CON FAMILIA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (403, 'SEGÚN SU TIA, TIENE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (593, 'SEGÚN SU TIA, TIENE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (619, 'SEGÚN ANGEL LE ESTAN DEVOLVIENTO LOS RECIBOS. SE QUEDAN LAS HERMANITAS CON TODO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (283, 'SE LE QUITA DE LA POLIZA DEFENSA JURÍDICA.PASA DE PAGAR 406,72 €  A 259,79€');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (234, 'REEMPLAZA A LA PÓLIZA Nº 0381480343750');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (300, 'PTE PEDIR PÓLIZA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (285, 'PRESUPUESTO RECIBIDO DE MªBEL(LIBERBANK)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (52, 'PÓLIZA QUE A PARTIR DE ABRIL-23 LO PAGARÁ LA TUTELADA. ANTES LO ABONABAN LAS HERMANAS.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (258, 'PÓLIZA INDIVIDUAL.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (13, 'PÓLIZA FAMILIAR CON SU MADRE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (215, 'POLIZA FAMILIAR');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (134, 'POLIZA DE TOMASA SANCHO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (643, 'PÓLIZA DE SU PADRE DIEGO NEVADO BERROCAL CON DNI 07037709P');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (711, 'PÓLIZA CONJUNTA CON SU HERMANO DE MADRE(ADELINO LOZANO GIL).SE DOMICILIA EN SU CUENTA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (351, 'POLIZA CON PADRE Y HERMANOS. 5-9-2023.lo saco de la póliza familiar y se lo hago a él solo.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (63, 'PÓLIZA COMPARTIDA CON BENEDICTA SIMON RIVERO.LO PAGA LA TUTELADA. EL 22-3-2022.SE SOLICITA BAJA EN CASER. 25-05-2022.ANULADA POLIZA CON CASER');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (273, 'PÓLIZA AL DÍA. CARGADA EN SU CUENTA EL 2-ENERO-2023');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (130, 'POLIZA A NOMBRE DE PADRE ELOY GONZALEZ JIMENEZ');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (296, 'POLIZA  FAMILIAR JUNTO CON SU HERMANO JOSÉ Mª. Se le hace una nueva poliza.5-11-2021');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (39, 'PENDIENTE RETIRAR DE LIBERBANK');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (106, 'PENDIENTE DE AVERIGUAR');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (456, 'PEDIR POLIZA BELEN');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (240, 'PEDIR DUPLICADO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (139, 'PEDIDOC CARTA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (225, 'PEDIDO POR CORREO ELECTRONICO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (29, 'PEDIDO COPIA 28/01');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (705, 'PEDIDO CARTA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (633, 'PEDIDO A GENERALI');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (41, 'PDF///ESTA JUNTO A SU MADRE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (74, 'PDF///EL NUMERO DE POLIZA NO FIGURA EN LA MISMA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (277, 'PDF///EL NUMERO DE POLIZA NO FIGURA EN LA MISMA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (326, 'PDF///EL NUMERO DE POLIZA NO FIGURA EN LA MISMA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (430, 'PDF///EL NUMERO DE POLIZA NO APARECE EN LA MISMA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (645, 'PDF///DOMICILIO PARTICULAR BADAJOZ');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (77, 'PDF///DOMICILIO FAMILIAR MIAJADAS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (562, 'PDF///A NOMBRE DE SU HERMANO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (521, 'PDF.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (622, 'PDF TAMBIEN SU HERMANO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (157, 'PDF A NOMBRE DE HERMANA JUANA CANCHALES MALDONADO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (12, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (45, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (64, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (90, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (95, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (98, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (151, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (175, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (184, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (188, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (221, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (239, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (246, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (270, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (323, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (375, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (405, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (449, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (475, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (477, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (485, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (493, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (508, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (613, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (615, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (629, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (644, 'PDF');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (235, 'PANTEON FAMILIAR EN CACERES');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (78, 'PAGO TRIMESTRAL DE 39,22€ QUE SE CARGA EN SU CUENTA DE CAJA RURAL DE EXTREMADURA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (570, 'PAGA LA MADRE. PEDIDA COPIA  EL 31-8-2022. Y EL 15-9-2022. NO ME LA ENVIAN POR LA LEY DE PROTECCIÓN DE DATOS. AL 23-9-22 ESTÁ AL DÍA EN EL PAGO SEGÚN SU HERMANA RUFINA.TLF.651655267');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (205, 'OK COPIA JUL2018');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (255, 'OK COPIA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (480, 'ocaso Badajoz MARÍA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (606, 'NÚMERO DE PÓLIZA 2.020.204.ESTÁ  SOLA DE  TITULAR.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (561, 'NUEVO///BLOQUEADAS CLAVES SANTANDER///LAMMAR AL HIJO, SEGÚN MARIVI');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (261, 'NO X EDAD según informe social no tiene seguro. Tiene 76 años.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (129, 'NO X EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (260, 'NO X EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (535, 'NO X EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (114, 'NO SUPONE OBLIGACION PARA NOSOTROS///CURATELA PARA LA SALUD///CRR DE MERIDA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (635, 'NO SE LE HACE PORQUE TIENE 88 AÑOS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (84, 'NO SE FORMALIZA POR EDAD.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (280, 'NO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (140, 'NO FORMALIZADO POR LA EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (5, 'NO FORMALIZADO POR ENFERMEDAD GRAVE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (359, 'NO FORMALIZADO POR EDAD///TIENE DINERO///FUNERARIA MORENO VILLAFRANCA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (318, 'NO FORMALIZADO POR EDAD. SOCIOSANITARIO DE PLASENCIA HACE TRANSFERNCIA A LA FUNERARIA POR LOS SERVICIOS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (3, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (23, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (30, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (69, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (117, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (121, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (133, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (137, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (138, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (150, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (155, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (177, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (202, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (233, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (242, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (243, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (247, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (253, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (268, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (278, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (284, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (288, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (295, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (305, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (311, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (316, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (325, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (338, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (339, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (340, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (365, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (368, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (374, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (381, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (443, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (444, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (448, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (463, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (473, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (514, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (515, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (539, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (548, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (556, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (557, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (558, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (564, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (582, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (592, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (602, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (603, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (604, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (665, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (677, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (692, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (693, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (695, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (697, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (704, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (706, 'NO FORMALIZADO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (182, 'NO FORMALIZADO  POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (712, 'NO FORMALIZACO POR EDAD');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (694, 'NICHO PROPIO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (646, 'NACIDA EN 1935. TIENE NICHO  EN PROPIEDAD CON Nº9994. EN EL CEMENTERIO DE CÁCERES.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (269, 'MENSUAL 9,74 IBERCAJA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (636, 'me confirman desde la  residencia que no tiene seguro,no se lo hago.tiene 92 años.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (377, 'mariaantonia.ortizvalle@ocaso.es TOÑI 924453504  o4sd@ocaso.es');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (101, 'MADRE CORAZON 927227265///MARIDO 6092343280');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (293, 'LO PAGA SU HERMANO JUAN');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (478, 'LO ENVIARAN POR CORREO POSTAL');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (9, 'LLAMAR A SU CASA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (407, 'LE HAGO SEGURO CON SANTA LUCIA. LO DEVUELVE LA TUTELADA. A 25 ENERO 2023.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (424, 'LA PÓLIZA ESTÁ A NOMBRE DEL PADRE QUE YA HA FALLECIDO.LA PAGA EL TUTELADO.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (647, 'LA PÓLIZA ESTÁ A NOMBRE DE LA MADRE.LO PAGA ELLA. ISIDORA RUIZ NIETO CON DNI.07362255-R. 22-8-2023.SE DOMICILIA EL PAGO EN LA CUENTA DEL TUTELADO.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (573, 'la póliza es de su madre.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (159, 'JUNTO CON SU MADRE FELISA FELIPE TEOMIRO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (589, 'JUNTO CON SU HERMANA. Se le hace una póliza nueva a él solo.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (499, 'JUNTO CON LA FAMILIA///TFNO. HNA. (PAULA) 657156831');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (656, 'HOGAR DE ANCIANOS JOSE NAZARENO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (100, 'HABLO CON VIRGINIA.927629824');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (158, 'HABLADO CON NTRA. SRA. DE LAS CRUCES, LO ENVIARA UNA PRIMA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (136, 'GARCIA GALAN Y DIEZ///CON SU MADRE Y DOS HERMANOS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (105, 'GARCIA GALAN Y DIAZ///CON SU MADRE Y DOS HERMANOS');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (160, 'FUNERARIA BARRADAS  EN VILLAFRANCA DE LOS BARROS  TIENE PAGADO FUNERAL PDF EN EXPEDIENTE.SE AMPLIA CANTIDAD DE GASTOS DEL FUNERAL');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (433, 'FORMALIZADO 20/05/2018');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (230, 'ESTRELLA.SE CARGA EN LA CUENTA DE SU HERMANO ANTONIO.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (60, 'ESTAN EN LA MISMA PÓLIZA LOS TRES HERMANOS.(ISABEL,PILAR. ALONSO)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (213, 'ESTAN EN LA MISMA PÓLIZA LOS DOS HERMANOS.(LEANDRO Y JESÚS)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (331, 'ESTÁN EN LA MISMA PÓLIZA LOS DOS HERMANOS(LEANDRO Y JESÚS)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (108, 'estamos intentando averiguar si tiene seguro, en el informe social no consta');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (79, 'ESTÁ EN UNA PÓLIZA CON LOS PADRES. ÉL NO PAGA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (631, 'está en la póliza de su hermano,  ella no tiene dinero');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (126, 'ESTÁ EN  UNA PÓLIZA CON  SUS PADRES.EL PADRE FALLECIDO.PAGA LA PÓLIZA LA MADRE.AL 20-10-2022 EL PAGO ESTÁ AL DÍA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (313, 'ESTÁ CON SU MADRE EN POLIZA Y LO PAGA LA MADRE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (217, 'ESTA CON SU MADRE EN NORTEHISPANA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (511, 'en la poliza con el hermano y la cuñada. La cuñada es la tomadora');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (482, 'EN LA MISMA PÓLIZA ESTÁN LOS TRES HERMANOS.(PILAR,ISABEL ALONSO)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (530, 'EN LA MISMA PÓLIZA ESTÁN LOS TRES HERMANOS.(ISABEL,PILAR,ALONSO)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (297, 'en la misma póliza está su hermana Manuela.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (423, 'DOMICILIO FAMILIAR CACERES.TIENE SEGURO DEL HOGAR CON MAPFRE Y SEGURO DECESO CON MAPFRE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (490, 'CRR DE MERIDA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (416, 'COPIA OK');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (517, 'COPIA OK');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (429, 'CON SU MADRE VICTORIANA HERNANDEZ');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (657, 'CON SU HIJO MARTIN MIRANDA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (248, 'CON SU HERMANA. Lo cargan en su cuenta en liberbank.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (187, 'COMPARTIDO CON FLORA GUTIERREZ GARCIA (HIJA)');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (46, 'C.A.M.F. DE ALCUESCAR');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (551, 'ASEGURADO CON SU MADRE SEGUN TERESA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (462, 'ANUAL///COPIA OK');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (210, 'ACTUALIZADO 2019');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (559, 'A NOMBRE DE SU PADRE JOSÉ PÉREZ CORTES 08646796S');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (506, 'A NOMBRE DE SU HERMANO FRANCISCO///SEGURO DE VIVIENDA CON MAPFRE');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (358, 'A NOMBRE DE SU HERMANA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (131, 'A NOMBRE DE PEDRO GONZALEZ PINTO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (527, '8-3-2023.LA PÓLIZA ESTÁ A NOMBRE DE SU HERMANA CONCEPCIÓN Y PAGA ELLA TAMBIÉN.A LA FECHA DE HOY ESTÁ AL CORRIENTE EN EL PAGO.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (642, '605612560/RAUL PEDIR A GENERALI///DOMICILIO PARTICULAR PLASENCIA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (312, '27-2-2023-COMUNICO A LA COMPAÑÍA  EL Nº DE CTA. ANTES SE LO PAGABA SU HERMANA ISABEL. 13-3-2023.ya está la poliza a nombre del tutelado.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (208, '27-10-2022.LE CAMBIO EL Nº DE CTA.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (354, '13-6-2023-ESTRELLA-NO TIENE CONTRATADA LA LÁPIDA.HABLO CON CELES Y ME COMENTA QUE AL TENER UN CAPITAL CONTRATADO DE 4.129 €, ES MEJOR DEJAR LA PÓLIZA ASÍ.SE PUEDE SOLICITAR LA DEVOLUCIÓN DEL CAPITAL QUE NO USE, Y CON ESA DEVOLUCIÓN SE PUEDE ABONAR LA LÁPIDA');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (371, '12-7-2023.LA PÓLIZA LA PAGA LA MADRE(BENITA.TLF.628887928)OCASO ME CONFIRMA QUE AL DÍA DE HOY ESTÁ AL CORRIENTE EN EL PAGO Y QUE YA ESTÁ BIEN PUESTA SU FECHA DE NACIMIENTO.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (190, '10-3-2022-ESTÁ EN LA MISMA PÓLIZA CON SU PADRE.A LA ESPERA DE HACERLE EL SEGURO A ELLA SOLA. 26-05-2022.YA TIENE POLIZA INDIVIDUAL.');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (696, '10-11-2022.DADO DE BAJA MAPFRE.PAGABA DOS SEGUROS DE DECESO');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (4, '003571240000SDD000503445');
INSERT INTO gestion_seguros_decesos(expediente_id, observaciones) VALUES (165, '??');
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (2);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (6);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (7);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (8);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (10);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (11);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (16);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (17);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (18);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (19);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (20);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (21);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (22);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (24);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (25);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (26);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (27);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (31);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (32);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (33);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (34);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (35);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (36);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (37);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (38);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (40);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (42);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (44);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (47);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (48);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (49);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (50);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (51);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (53);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (54);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (55);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (56);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (57);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (58);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (59);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (61);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (62);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (65);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (66);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (67);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (68);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (71);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (72);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (73);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (75);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (76);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (81);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (82);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (85);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (87);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (88);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (89);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (91);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (92);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (93);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (94);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (96);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (97);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (103);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (104);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (107);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (109);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (110);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (111);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (112);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (113);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (115);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (116);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (118);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (119);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (120);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (122);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (123);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (124);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (125);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (127);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (128);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (135);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (141);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (143);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (144);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (145);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (146);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (147);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (148);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (149);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (152);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (153);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (154);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (156);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (161);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (162);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (163);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (164);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (166);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (168);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (169);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (170);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (171);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (172);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (173);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (174);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (176);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (178);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (179);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (180);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (181);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (185);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (186);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (189);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (191);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (192);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (193);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (195);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (196);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (197);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (198);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (199);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (200);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (201);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (203);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (204);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (207);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (209);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (211);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (212);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (214);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (216);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (218);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (219);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (220);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (222);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (223);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (224);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (226);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (227);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (228);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (229);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (231);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (232);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (236);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (237);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (238);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (241);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (244);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (245);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (249);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (250);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (251);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (252);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (254);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (256);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (257);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (259);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (263);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (264);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (265);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (266);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (267);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (271);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (272);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (274);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (275);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (279);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (281);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (282);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (286);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (287);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (289);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (290);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (291);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (292);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (294);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (298);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (299);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (301);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (302);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (303);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (304);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (306);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (307);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (308);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (309);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (310);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (314);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (315);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (317);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (319);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (320);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (321);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (322);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (324);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (327);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (328);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (329);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (330);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (332);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (334);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (335);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (336);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (337);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (341);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (342);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (344);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (345);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (346);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (347);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (348);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (349);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (350);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (352);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (353);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (355);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (356);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (357);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (360);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (361);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (362);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (363);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (364);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (366);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (367);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (369);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (370);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (372);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (373);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (376);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (378);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (379);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (380);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (382);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (383);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (384);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (386);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (387);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (390);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (391);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (392);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (393);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (394);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (395);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (396);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (397);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (398);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (399);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (400);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (401);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (402);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (404);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (408);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (409);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (410);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (411);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (412);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (413);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (414);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (415);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (418);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (419);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (420);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (422);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (425);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (426);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (427);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (428);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (431);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (432);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (434);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (435);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (436);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (437);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (438);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (439);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (440);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (441);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (442);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (445);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (446);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (450);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (451);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (452);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (453);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (454);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (455);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (457);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (458);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (459);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (460);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (461);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (464);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (465);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (466);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (467);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (468);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (469);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (470);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (471);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (472);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (474);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (476);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (479);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (481);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (483);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (484);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (486);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (487);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (488);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (489);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (491);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (492);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (495);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (496);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (497);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (500);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (501);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (502);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (503);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (504);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (505);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (509);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (510);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (512);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (516);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (518);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (519);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (522);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (523);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (524);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (525);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (526);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (528);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (529);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (531);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (532);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (533);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (534);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (536);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (537);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (538);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (540);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (541);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (542);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (543);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (544);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (545);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (546);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (547);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (549);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (550);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (552);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (553);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (554);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (555);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (560);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (563);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (565);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (566);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (567);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (568);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (569);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (571);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (572);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (574);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (575);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (576);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (577);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (578);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (579);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (581);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (583);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (584);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (585);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (586);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (587);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (588);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (590);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (591);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (594);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (595);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (596);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (597);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (598);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (599);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (601);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (605);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (607);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (608);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (609);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (610);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (611);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (612);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (614);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (616);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (618);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (620);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (621);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (623);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (624);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (625);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (626);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (627);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (628);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (630);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (632);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (637);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (638);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (639);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (640);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (641);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (648);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (649);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (650);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (651);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (652);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (653);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (654);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (655);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (658);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (659);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (660);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (661);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (662);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (663);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (664);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (666);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (668);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (669);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (670);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (671);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (672);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (673);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (674);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (675);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (676);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (678);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (679);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (680);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (681);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (682);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (683);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (684);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (685);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (686);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (687);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (688);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (689);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (691);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (698);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (699);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (700);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (701);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (702);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (703);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (707);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (708);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (709);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (710);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (713);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (714);
INSERT INTO gestion_seguros_decesos(expediente_id) VALUES (1);



