INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (256, 14);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (257, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (46, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (34, 15);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (204, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (318, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (27, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (334, 11);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (208, 10);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (246, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (377, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (243, 11);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (379, 7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (212, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (381, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (230, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (411, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (45, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (223, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (44, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (430, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (242, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (218, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (450, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (213, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (464, 11);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (482, 7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (492, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (197, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (516, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (525, 14);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (555, 11);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (110, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (565, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (575, 15);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (220, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (604, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (199, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (617, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (624, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (111, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (647, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (651, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (216, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (198, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (665, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (674, 20);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id) VALUES (52, 17);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza) VALUES (293, '030600759');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza) VALUES (523, '01356248-2');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (122, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (126, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (127, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (268, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (289, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (128, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (296, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (14, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (59, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (117, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (129, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (130, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (239, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (131, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (132, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (133, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (134, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (135, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (345, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (136, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (137, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (33, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (219, 7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (138, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (105, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (397, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (139, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (140, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (141, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (142, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (143, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (144, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (145, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (146, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (427, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (147, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (148, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (436, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (149, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (439, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (150, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (441, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (124, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (151, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (152, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (153, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (154, 7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (123, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (155, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (156, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (157, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (158, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (487, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (31, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (39, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (509, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (512, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (159, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (160, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (11, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (161, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (537, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (162, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (163, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (194, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (30, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (164, 7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (165, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (116, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (166, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (167, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (233, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (168, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (169, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (170, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (171, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (615, 2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (172, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (173, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (40, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (174, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (176, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (640, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (646, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (22, 7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (177, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (178, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (180, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (187, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (181, 6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (182, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (703, 3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (183, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (65, 4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (184, 5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, carpeta_deceso_id) VALUES (186, 1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (714, 17,'280034612');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (48, 20,'1754873');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (26, 14,'382180123388100');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (280, 15,'D09/135772');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (35, 20,'1.419.664');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (315, 17,'2710288');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (56, 20,'1363064');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (349, 17,'1311658');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (353, 17,'2.660.850');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (10, 20,'36038852');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (364, 14,'0382180059256');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (365, 11,'101.000.766');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (390, 17,'280041391');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (393, 14,'077-9300650775');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (413, 17,'1153920');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (120, 14,'0731280454609');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (448, 20,'1.758.817');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (449, 14,'0809980157850');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (461, 17,'280031941');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (462, 3,'0822035');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (53, 20,'28305');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (472, 20,'36.027.362');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (191, 17,'3210007893');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (490, 14,'0382180096459');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (491, 20,'1430072');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (514, 20,'171410001');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (533, 17,'280040027');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (545, 14,'0382180096435');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (225, 6,'99950116/60492');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (580, 3,'126505');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (581, 20,'149003766');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza) VALUES (609, 20,'833351');
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (248, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (253, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (195, 3,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (254, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (255, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (259, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (260, 20,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (262, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (263, 20,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (264, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (266, 11,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (270, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (271, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (273, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (274, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (276, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (277, 17,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (232, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (286, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (287, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (211, 17,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (291, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (54, 2,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (294, 15,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (68, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (299, 2,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (215, 14,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (303, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (5, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (304, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (305, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (306, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (307, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (308, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (311, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (312, 6,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (192, 20,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (314, 11,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (323, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (324, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (325, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (326, 6,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (328, 6,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (24, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (50, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (62, 12,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (335, 3,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (336, 3,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (338, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (339, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (84, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (341, 6,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (343, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (346, 6,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (348, 7,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (249, 6,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (350, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (358, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (360, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (361, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (367, 6,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (18, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (368, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (369, 20,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (371, 20,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (376, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (378, 6,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (383, 14,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (384, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (385, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (388, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (210, 6,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (398, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (399, 6,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (90, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (404, 11,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (405, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (407, 19,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (47, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (408, 11,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (6, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (409, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (55, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (417, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (38, 14,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (69, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (42, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (422, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (425, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (426, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (57, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (428, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (429, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (431, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (432, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (433, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (438, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (445, 11,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (92, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (446, 12,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (70, 11,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (447, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (7, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (452, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (453, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (454, 12,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (457, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (36, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (459, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (460, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (463, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (244, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (468, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (469, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (238, 21,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (470, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (475, 20,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (477, 17,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (478, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (479, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (480, 20,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (485, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (486, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (488, 6,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (25, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (494, 6,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (495, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (498, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (502, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (1, 20,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (511, 11,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (19, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (515, 3,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (224, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (519, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (71, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (520, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (522, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (527, 17,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (528, 6,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (530, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (536, 14,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (60, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (539, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (540, 20,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (541, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (543, 17,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (550, 3,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (551, 6,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (552, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (96, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (554, 20,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (556, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (221, 17,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (558, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (562, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (563, 17,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (564, 11,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (8, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (202, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (569, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (570, 3,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (571, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (572, 17,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (573, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (237, 7,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (15, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (100, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (9, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (577, 6,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (578, 12,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (12, 11,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (584, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (240, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (585, 17,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (586, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (222, 17,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (589, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (590, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (594, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (595, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (597, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (598, 14,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (599, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (600, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (601, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (602, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (607, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (236, 17,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (112, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (611, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (614, 6,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (107, 11,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (616, 3,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (619, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (620, 6,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (621, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (23, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (626, 6,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (631, 20,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (634, 14,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (635, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (636, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (28, 15,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (644, 11,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (645, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (32, 12,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (648, 20,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (41, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (652, 6,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (653, 6,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (654, 11,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (655, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (656, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (657, 6,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (66, 11,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (659, 14,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (660, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (661, 14,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (662, 6,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (241, 11,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (51, 20,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (664, 6,5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (666, 2,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (670, 14,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (203, 6,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (672, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (673, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (675, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (677, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (13, 14,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (680, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (681, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (683, 17,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (684, 14,2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (690, 17,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (693, 20,1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (697, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (698, 14,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (699, 20,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (700, 17,4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (247, 20,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (702, 20,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (704, 17,3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (706, 17,7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,carpeta_deceso_id) VALUES (709, 6,6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza,carpeta_deceso_id) VALUES (67, 'R-04286704-7',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza,carpeta_deceso_id) VALUES (86, '8045535-6',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza,carpeta_deceso_id) VALUES (109, '3498466-2',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza,carpeta_deceso_id) VALUES (437, '7179190-4',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza,carpeta_deceso_id) VALUES (75, '3210038682',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, poliza,carpeta_deceso_id) VALUES (687, '7.020.641-2',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (251,17,'647675',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (252,20,'0382180196100/000',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (78,20,'116.019.330',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (258,14,'0381280192429',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (261,14,'0381680232453',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (265,14,'0360340828690',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (3,20,'149.011.364',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (64,20,'674043463',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (269,14,'038-1280148250',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (272,14,'0381680166944',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (58,6,'0099933101',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (275,14,'0381680232552',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (17,14,'0382080043637',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (79,20,'1.612.375',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (278,20,'1.173.082',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (279,14,'0382080138767',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (283,6,'5960084',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (284,14,'0381480320057',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (285,14,'0381680167465',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (288,14,'0381680231021',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (290,6,'99933116/13288',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (80,17,'280022014',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (295,6,'995016/36118',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (37,14,'0381480343803',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (297,14,'0381680232630',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (298,14,'0381480343254',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (300,20,'731.035.707',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (302,14,'0381480319823',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (81,14,'0382080011777',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (309,14,'0381680270963',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (310,6,'99950116/26722',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (82,20,'10.004.463',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (83,12,'B1 Z02 0009896',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (313,6,'99950116/31915',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (207,15,'D09/135538',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (316,14,'0381480319899',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (317,20,'527.089',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (320,14,'0381680239989',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (321,22,'0231220',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (322,14,'0381280192460',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (327,14,'0381380472571',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (329,20,'149010187',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (217,17,'1210034447',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (330,11,'NO CONSIGNADO EN POLIZA',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (331,20,'0001758801',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (332,6,'99950116/62193',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (206,15,'D09/135538',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (337,14,'0381280192484',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (340,14,'0381680172113',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (342,14,'0381480319988',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (344,17,'1960001316',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (77,20,'177.036.735',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (205,14,'Nº: 0382080186840',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (347,6,'00006507-002',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (351,20,'10.008.743',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (354,14,'0381480319858',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (355,14,'0381780234056',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (356,14,'0381680260507',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (85,17,'2261697',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (357,14,'0381480320295',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (359,14,'0381680159627',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (362,14,'0381480332945',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (363,6,'99950116/57448',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (231,20,'17055482',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (87,14,'0809980060821',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (370,20,'177055743',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (372,14,'0381680231025',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (373,17,'177.051.595',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (374,14,'0381680273843',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (375,14,'0381680167228',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (108,15,'24186',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (235,14,'0381580238657',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (49,12,'C1W000522481',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (382,14,'0381680240321',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (88,14,'0381680260481',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (386,14,'0381480570338',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (387,20,'58043903',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (63,20,'981.696',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (389,6,'00009806',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (391,14,'0381680241259',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (43,14,'0381880199518',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (395,14,'0381680167465',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (396,9,'70897',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (89,14,'0381580076837',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (61,20,'21.021.006',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (403,20,'58053502',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (406,6,'0779300651989',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (410,14,'0381480320259',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (189,17,'21000-178918',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (91,14,'0381680232440',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (414,14,'0381680167477',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (415,14,'0381480319936',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (416,14,'0381780068248',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (418,6,'99950116/62655',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (420,14,'0381680268674',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (423,14,'0381680167224',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (424,20,'607.010.530',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (193,20,'115.011.457',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (434,14,'0381480320140',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (435,6,'99950116/59924',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (442,14,'0381680166994',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (443,14,'0381480570320',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (444,14,'0381580460575',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (455,14,'0381480571908',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (456,14,'0381680167015',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (458,12,'XB Z02 00002792',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (466,14,'080978008009',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (467,14,'0381380190197',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (474,14,'0381680232450',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (245,17,'2743465',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (93,17,'401645',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (484,20,'0381680251052',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (489,6,'99950116',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (4,20,'149.011.364',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (496,14,'0381680167428',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (497,14,'0381480320105',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (499,17,'647695',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (500,14,'0381480343770',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (501,14,'0381480320019',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (503,14,'0371580254941',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (94,14,'0381980071659/000',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (507,17,'1870015046',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (508,20,'1.070.440',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (510,12,'B1Z010005449',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (226,15,'D18/003891',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (513,6,'99950116/62196',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (517,14,'0381680240356',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (518,14,'0382280203567/000',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (228,20,'486.618',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (209,11,'07-G-060.010.041',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (529,20,'0381680179698',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (531,14,'0381680167242',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (532,14,'0381680286495',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (95,17,'280022014',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (234,11,'07-G-060.010.369',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (544,6,'00062956',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (548,14,'0381680179701',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (549,14,'0381480343206',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (553,17,'1870014894',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (97,6,'99950116/60561',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (98,15,'D16/001893',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (559,14,'0381480320336',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (560,17,'1210036903',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (561,14,'0381680145149',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (99,21,'0251025',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (566,20,'1076536',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (568,14,'0381680249826',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (574,6,'61000002-70009572',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (227,20,'602062771',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (579,17,'270012756',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (583,14,'0381680235655',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (587,14,'0779300650742',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (588,14,'0381580195801',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (596,20,'731018467',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (603,20,'449317',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (606,14,'0381680260500',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (608,6,'99950116/60312',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (74,20,'1.482.501',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (612,14,'0381680260488',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (613,14,'0381680239983',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (622,14,'0381280148816',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (623,14,'0381680235652',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (627,14,'0381680236201',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (628,14,'0381680240382',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (629,14,'0381680260531',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (201,20,'560.579',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (630,14,'0381480343727',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (632,14,'0381680145158',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (633,11,'07-G-060.009.338',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (637,14,'0381680268666',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (638,17,'1210038297',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (639,14,'0381680042341/005',7);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (641,14,'0381680145149',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (642,14,'0381480320176',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (643,14,'0381480343743',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (101,17,'1870014903',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (102,17,'1210031768',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (649,14,'0381680167201',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (650,6,'99950111/60493',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (76,20,'116.026.561',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (103,1,'D09/059514',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (658,14,'0381480343307',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (663,14,'0381680179703',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (104,12,'B1 W00 1250557',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (72,14,'0381980252812',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (667,6,'99950116/59945',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (669,20,'177.054,794',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (671,14,'0381680231511',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (229,20,'486.618',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (676,14,'0381680260524',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (678,14,'0381680159622',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (679,14,'0381680167437',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (682,14,'0381480343683',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (685,14,'0381480319775',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (686,14,'0381280148530',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (688,20,'750301',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (689,11,'07-G-060.009.125',1);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (691,14,'0381680268661',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (692,17,'178.928',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (694,17,'3750013613',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (695,14,'0381480319691',5);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (696,14,'0381280192653',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (2,20,'185.628.759',6);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (701,14,'0381680167010',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (179,2,'000001596',2);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (705,14,'0381480570283',4);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (707,14,'0381480322156',3);
INSERT INTO seguro_decesos(gestion_seguro_deceso_id, aseguradora_id,poliza,carpeta_deceso_id) VALUES (708,14,'0381680232572',1);
