
update expediente_patologia_concreta set patologia_concreta_id= 8 where patologia_concreta_id=7 or patologia_concreta_id=8 or patologia_concreta_id=9 or patologia_concreta_id=13 or patologia_concreta_id=14;
update expediente_patologia_concreta set patologia_concreta_id= 37 where patologia_concreta_id=36 or patologia_concreta_id=37;
update patologia_concreta set nombre='CATARATA OJO DERECHO' where id=42 and nombre='CATARA OJO DERECHO';
update patologia_concreta set nombre='DISCAPACIDAD SISTEMA OSTEOARTICULAR' where id=108 and nombre='DISC. SISTEMA OSTEOARTICULAR';
update expediente_patologia_concreta set patologia_concreta_id= 113 where patologia_concreta_id=112 or patologia_concreta_id=113;
update expediente_patologia_concreta set patologia_concreta_id= 75 where patologia_concreta_id=75 or patologia_concreta_id=76;
update patologia_concreta set nombre='ENFERMEDAD ESOFAGO' where id=133 and nombre='ENF. ESOFAGO ';
update patologia_concreta set nombre='ENFERMEDAD HEPATICA CRONICA' where id=134 and nombre='ENF. HEPATICA CRONICA ';
update patologia_concreta set nombre='ENFERMEDAD VASCULAR PERIFERICA' where id=135 and nombre='ENF. VASCULAR PERIFERICA';
update expediente_patologia_concreta set patologia_concreta_id= 181 where patologia_concreta_id=181 or patologia_concreta_id=183;
update patologia_concreta set nombre='INFLUENCIABLE' where id=199 and nombre='INFUENCIABLE';
update expediente_patologia_concreta set patologia_concreta_id= 204 where patologia_concreta_id=202 or patologia_concreta_id=203;
update patologia_concreta set nombre='PARESIA NERVIO PERIFERICO' where id=234 and nombre='PAREXIA NERVIO PERIFERICO';
update expediente_patologia_concreta set patologia_concreta_id= 267 where patologia_concreta_id=263 ;
update expediente_patologia_concreta set patologia_concreta_id= 271 where patologia_concreta_id=273 ;
update expediente_patologia_concreta set patologia_concreta_id= 279 where patologia_concreta_id=278 ;
update expediente_patologia_concreta set patologia_concreta_id= 283 where patologia_concreta_id=288 ;
update expediente_patologia_concreta set patologia_concreta_id= 297 where patologia_concreta_id=296 ;
update expediente_patologia_concreta set patologia_concreta_id= 302 where patologia_concreta_id=303 ;
update expediente_patologia_concreta set patologia_concreta_id= 307 where patologia_concreta_id=308 ;
update expediente_patologia_concreta set patologia_concreta_id= 337 where patologia_concreta_id=309 OR patologia_concreta_id=329 OR patologia_concreta_id=331 OR patologia_concreta_id=399 ;
update expediente_patologia_concreta set patologia_concreta_id= 342 where patologia_concreta_id=345 OR patologia_concreta_id=386;
update expediente_patologia_concreta set patologia_concreta_id= 372 where patologia_concreta_id=388 ;
update patologia_concreta set nombre='TRASTORNO SOMATOMORFO' where id=403 and nombre='TRATORNO SOMATOMORFO ';
update expediente_patologia_concreta set patologia_concreta_id= 376 where patologia_concreta_id=311 ;
update expediente_patologia_concreta set patologia_concreta_id= 391 where patologia_concreta_id=312 ;
update expediente_patologia_concreta set patologia_concreta_id= 313 where patologia_concreta_id=357 ;
update expediente_patologia_concreta set patologia_concreta_id= 335 where patologia_concreta_id=334 ;
delete from patologia_concreta where id=7 and nombre='ALTERACION CONDUCTA';
delete from patologia_concreta where id=9 and nombre='ALTERACION DE LA CONDUCTA';
delete from patologia_concreta where id=13 and nombre='ALTERACIONES CONDUCTUALES';
delete from patologia_concreta where id=14 and nombre='ALTERACIONES DE CONDUCTA';
delete from patologia_concreta where id=36 and nombre='C.I.LIMITE';
delete from patologia_concreta where id=107 and nombre='DISC. SIST. OSTEOARTICULAR';
delete from patologia_concreta where id=112 and nombre='DISCAPACIDAD INTELECTIVA';
delete from patologia_concreta where id=202 and nombre='LIM. FUNC. COLUMNA';
delete from patologia_concreta where id=203 and nombre='LIM. FUNCIONAL COLUMNA';
delete from patologia_concreta where id=76 and nombre='DEPENDENCIA ALCOHOLICA';
delete from patologia_concreta where id=183 and nombre='HIPERTESION';
delete from patologia_concreta where id=223 and nombre='OLIGROFENIA';
delete from patologia_concreta where id=224 and nombre='OLIGROFRENIA';
delete from patologia_concreta where id=216 and nombre='nombre';
delete from patologia_concreta where id=263 and nombre='RETRAS MENTAL GRAVE';
delete from patologia_concreta where id=273 and nombre='RETRASO MENTAL MODERANO';
delete from patologia_concreta where id=278 and nombre='SINDORME ANSIOSO-DEPRESIVO';
delete from patologia_concreta where id=288 and nombre='SINDROME DOWN';
delete from patologia_concreta where id=296 and nombre='SODERA';
delete from patologia_concreta where id=303 and nombre='TDHA';
delete from patologia_concreta where id=308 and nombre='TOXICOMANO';
delete from patologia_concreta where id=309 and nombre='TRANSTORNO CONDUCTA';
delete from patologia_concreta where id=329 and nombre='TRASTORNO CONDUCTA';
delete from patologia_concreta where id=331 and nombre='TRASTORNO CONDUCTUAL';
delete from patologia_concreta where id=399 and nombre='TRASTORNOS DE CONSUCTA';
delete from patologia_concreta where id=345 and nombre='TRASTORNO DE PERSONALIDAD';
delete from patologia_concreta where id=386 and nombre='TRASTORNO PERSONALIDAD';
delete from patologia_concreta where id=388 and nombre='TRASTORNO PERSONALIDAD HISTRIONICO';
delete from patologia_concreta where id=310 and nombre='TRANSTORNO MENTAL';
delete from patologia_concreta where id=311 and nombre='TRANSTORNO MIXTO PERSONALIDAD';
delete from patologia_concreta where id=312 and nombre='TRANSTORNO PSICOTICO';
delete from patologia_concreta where id=357 and nombre='TRASTORNO DESARROLLO';
delete from patologia_concreta where id=334 and nombre='TRASTORNO CONTROL IMPULSO';




