UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 02/03' WHERE (`numero_documento` = '76263077E');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'MONTANCHEZ. PENDIENTE APROBACION 03/12' WHERE (`numero_documento` = '07017225V');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION' WHERE (`numero_documento` = '28954137N');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.JUZGADO Nº 4  BADAJOZ: NO HECER RENDICIÓN' WHERE (`numero_documento` = '80092306G');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.LINEA CB      pendiente aprobacion' WHERE (`numero_documento` = '53262645G');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 01/12' WHERE (`numero_documento` = '811791600Y');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.SE MANDA A BURGOS' WHERE (`numero_documento` = '06961798C');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.SERVICASH' WHERE (`numero_documento` = '07016503P');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.YA TIENE INFORME' WHERE (`numero_documento` = '28959754V');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 21/10' WHERE (`numero_documento` = '34770094M');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.ES UNA CURATELA SÓLO PARA EL TRATAMIENTO DE LA ENF' WHERE (`numero_documento` = '08383837W');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'MADRIGALEJO.PENDIENTE APROBACION FISCALIA' WHERE (`numero_documento` = '50938312M');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 16-12' WHERE (`numero_documento` = '80044285F');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 26/04' WHERE (`numero_documento` = '09198213F');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION  21/02' WHERE (`numero_documento` = '52207416S');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 30/05' WHERE (`numero_documento` = '76229968X');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'ZALAMEA DE LA SERENA.PENDIENTE APROBACION 02/03' WHERE (`numero_documento` = '39713423J');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 3/11 AVILA' WHERE (`numero_documento` = '04185263E');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 25/07' WHERE (`numero_documento` = '11634360 5 ZX4');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 30-08' WHERE (`numero_documento` = '53267334R');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION  25/03' WHERE (`numero_documento` = '08867679Y');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'ALMENDRALEJO.PEDIENTE APROBACION 20-08' WHERE (`numero_documento` = '33976325N');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 21/09' WHERE (`numero_documento` = '51693229Q');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'ALMENDRALEJO.PENDIENTE APROBACION 14-01' WHERE (`numero_documento` = '34773154Y');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION  21/10' WHERE (`numero_documento` = '28960458P');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PTE. APROBACION 03/07' WHERE (`numero_documento` = '06923201V');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 16/12/09' WHERE (`numero_documento` = '76007252A');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 25/07' WHERE (`numero_documento` = '76036617C');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION' WHERE (`numero_documento` = '80028621Y');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 03/03' WHERE (`numero_documento` = '11765052T');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACIÓN 15/04' WHERE (`numero_documento` = '80015091T');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 25/07' WHERE (`numero_documento` = '08849740F');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 21/10' WHERE (`numero_documento` = '00395176J');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 22/02' WHERE (`numero_documento` = '06933207H');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 13/10' WHERE (`numero_documento` = '00395177Z');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION27/07' WHERE (`numero_documento` = '76188499X');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 10/05' WHERE (`numero_documento` = '08868297A');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.HAY CAMBIO DE JUZGADO AHORA LO LLEVA EL Nº 4 PLASE' WHERE (`numero_documento` = '11771590Y');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'BADAJOZ.PENDIENTE APROBACION  28.-08' WHERE (`numero_documento` = '08821107D');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PEDIENTE DE APROBACION 15/12/2009' WHERE (`numero_documento` = '76032844L');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 13/12' WHERE (`numero_documento` = '80090032F');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 15-07' WHERE (`numero_documento` = 'X2001267Z');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'FUENTE DEL MAESTRE.ENTREGA LA TOTALIDAD DE LA PENSION A LA RESIDENCIA' WHERE (`numero_documento` = '40279874C');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 22-03' WHERE (`numero_documento` = '76036616L');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 16/03' WHERE (`numero_documento` = '44778744K');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION  16/03' WHERE (`numero_documento` = '08622911G');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.SERVICASH' WHERE (`numero_documento` = '07016502F');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 29-12' WHERE (`numero_documento` = '52960588Y');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'CALERA DE LEÓN.PENDIENTE APROBACION' WHERE (`numero_documento` = '80037097H');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'MONESTERIO.PENDIENTE APROBACION' WHERE (`numero_documento` = '80011502E');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 21/10' WHERE (`numero_documento` = '76138007A');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 25/01' WHERE (`numero_documento` = '11777579S');
UPDATE `ctaex`.`expedientes` SET `aprob_inventario` = '', `observaciones_inv` = 'NO.PENDIENTE APROBACION 01/12' WHERE (`numero_documento` = '11791600Y');



