/*insercionn de nuevas patologias concretas*/
INSERT INTO patologia_concreta (nombre) values ('DEFICIENCIA EXPRESIVA');
INSERT INTO patologia_concreta (nombre) values ('DEFICIENCIA SISTEMA NERVIOSO Y MUSCULAR');
INSERT INTO patologia_concreta (nombre) values ('LIMITACION FUNCIONAL EN AMBOS MMII');
INSERT INTO patologia_concreta (nombre) values ('CADASIL');

/*insercion expediente_patologia_concreta de expedientes introducidos en base roja tras la primera descarga de la tabla que hicimos en su dia, estos datos son en referencia a la tabla
descargada a fecha 23/10/2024*/
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='SARAIT' and apellido1='GOMEZ' and apellido2='SIRUELA'), (select id from patologia_concreta where nombre='ESQUIZOFRENIA PARANOIDE'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='YOLANDA' and apellido1='MARTIN' and apellido2='VELASCO'), (select id from patologia_concreta where nombre='ALTERACION DE CONDUCTA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='YOLANDA' and apellido1='MARTIN' and apellido2='VELASCO'), (select id from patologia_concreta where nombre='TRASTORNO COGNITIVO'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PETRA' and apellido1='BARRERA' and apellido2='GONZALEZ'), (select id from patologia_concreta where nombre='TRASTORNO MENTAL'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PETRA' and apellido1='BARRERA' and apellido2='GONZALEZ'), (select id from patologia_concreta where nombre='ALTERACION DE CONDUCTA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JONATAN' and apellido1='GARCIA' and apellido2='TERRON'), (select id from patologia_concreta where nombre='DISCAPACIDAD INTELECTUAL LEVE'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JOSE LUIS' and apellido1='AVILA' and apellido2='FEMIA'), (select id from patologia_concreta where nombre='RETRASO MENTAL LIGERO'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JOSE LUIS' and apellido1='AVILA' and apellido2='FEMIA'), (select id from patologia_concreta where nombre='TRASTORNO DELIRANTE'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PRUDENCIO' and apellido1='RODERO' and apellido2='COMERON'), (select id from patologia_concreta where nombre='CADASIL'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JOSE MIGUEL' and apellido1='CORDERO' and apellido2='MASA'), (select id from patologia_concreta where nombre='ALTERACION DE CONDUCTA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JOSE MIGUEL' and apellido1='CORDERO' and apellido2='MASA'), (select id from patologia_concreta where nombre='TRASTORNO AFECTIVIDAD'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JOSE MIGUEL' and apellido1='CORDERO' and apellido2='MASA'), (select id from patologia_concreta where nombre='DEFICIENCIA EXPRESIVA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='JOSE MIGUEL' and apellido1='CORDERO' and apellido2='MASA'), (select id from patologia_concreta where nombre='SORDERA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'), (select id from patologia_concreta where nombre='TRASTORNO COGNITIVO'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'), (select id from patologia_concreta where nombre='DISCAPACIDAD INTELECTUAL'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'), (select id from patologia_concreta where nombre='DEFICIENCIA SISTEMA NERVIOSO Y MUSCULAR'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'), (select id from patologia_concreta where nombre='HEMIPARESIA IZQUIERDA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'), (select id from patologia_concreta where nombre='TRASTORNO SISTEMA ENDOCRINO-METABOLICO'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='GLORIA' and apellido1='VERA' and apellido2='LLORENTE'), (select id from patologia_concreta where nombre='PERDIDA AGUDEZA VISUAL'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='MIGUEL ANGEL' and apellido1='MONROY' and apellido2='FERNANDEZ'), (select id from patologia_concreta where nombre='DISCAPACIDAD INTELECTUAL MODERADA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='FEDERICO' and apellido1='APONTE' and apellido2='SOLIS'), (select id from patologia_concreta where nombre='ALTERACION DE CONDUCTA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='FEDERICO' and apellido1='APONTE' and apellido2='SOLIS'), (select id from patologia_concreta where nombre='LIMITACION FUNCIONAL MSD'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='FEDERICO' and apellido1='APONTE' and apellido2='SOLIS'), (select id from patologia_concreta where nombre='LIMITACION FUNCIONAL EN AMBOS MMII'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PRUDENCIA' and apellido1='GALINDO' and apellido2='PULIDO'), (select id from patologia_concreta where nombre='TRASTORNO AFECTIVIDAD'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PRUDENCIA' and apellido1='GALINDO' and apellido2='PULIDO'), (select id from patologia_concreta where nombre='LIMITACION FUNCIONAL DE COLUMNA'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PRUDENCIA' and apellido1='GALINDO' and apellido2='PULIDO'), (select id from patologia_concreta where nombre='DISCAPACIDAD SISTEMA OSTEOARTICULAR'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='PRUDENCIA' and apellido1='GALINDO' and apellido2='PULIDO'), (select id from patologia_concreta where nombre='PARESIA NERVIO PERIFERICO'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='ALEJANDRO' and apellido1='LOPEZ' and apellido2='GILARTE'), (select id from patologia_concreta where nombre='TRASTORNO MENTAL'));
INSERT INTO expediente_patologia_concreta (expediente_id,patologia_concreta_id) values ((select ei.id from expedientes_intranet ei inner join expediente_datos_personales edp on edp.id=ei.expediente_datos_personales_id where edp.nombre='ALEJANDRO' and apellido1='LOPEZ' and apellido2='GILARTE'), (select id from patologia_concreta where nombre='RETRASO MADURATIVO'));
