INSERT INTO prestaciones (nombre)values ('CLASES PASIVAS');
INSERT INTO prestaciones (nombre)values ('CLASES PASIVAS ORFANDAD FAM RETIRADOS');
INSERT INTO prestaciones (nombre)values ('CLASES PASIVAS PF');
INSERT INTO prestaciones (nombre)values ('CLASES PASIVAS PRESTACION HIJO MINUSVALIDO');
INSERT INTO prestaciones (nombre)values ('ECONOMICA VINCULADA AL SERVICIO');
INSERT INTO prestaciones (nombre)values ('EXTRANJERO');
INSERT INTO prestaciones (nombre)values ('FAMILIARES DE MILITARES');
INSERT INTO prestaciones (nombre)values ('IMV');
INSERT INTO prestaciones (nombre)values ('INCAPACIDAD ABSOLUTA ENFERMEDAD COMUN');
INSERT INTO prestaciones (nombre)values ('INCAPACIDAD PERMANENTE ABSOLUTA');
INSERT INTO prestaciones (nombre)values ('INCAPACIDAD PERMANENTE TOTAL');
INSERT INTO prestaciones (nombre)values ('ISFAS');
INSERT INTO prestaciones (nombre)values ('ISFAS PF');
INSERT INTO prestaciones (nombre)values ('JUBILACION');
INSERT INTO prestaciones (nombre)values ('JUBILACION DERIVADA PNC INVALIDEZ');
INSERT INTO prestaciones (nombre)values ('JUBILACION GRAN INVALIDEZ');
INSERT INTO prestaciones (nombre)values ('JUBILACION PROCEDENTE DE IPA');
INSERT INTO prestaciones (nombre)values ('JUBILACION PROCEDENTE DE IPT');
INSERT INTO prestaciones (nombre)values ('LISMI');
INSERT INTO prestaciones (nombre)values ('MUFACE');
INSERT INTO prestaciones (nombre)values ('NOMINA');
INSERT INTO prestaciones (nombre)values ('ORFANDAD');
INSERT INTO prestaciones (nombre)values ('ORFANDAD ABSOLUTA');
INSERT INTO prestaciones (nombre)values ('ORFANDAD CLASES PASIVAS');
INSERT INTO prestaciones (nombre)values ('PENSION A FAVOR DE FAMILIARES');
INSERT INTO prestaciones (nombre)values ('PENSION COMPENSATORIA');
INSERT INTO prestaciones (nombre)values ('PNC');
INSERT INTO prestaciones (nombre)values ('PNC INCAPACIDAD');
INSERT INTO prestaciones (nombre)values ('PRESTACION ECCA. CUIDADOS ENTORNO FAMILIAR');
INSERT INTO prestaciones (nombre)values ('PRESTACION ECCA. VINCULADA AL SERVICIO');
INSERT INTO prestaciones (nombre)values ('PROTECCION FAMILIAR');
INSERT INTO prestaciones (nombre)values ('RENTA EXTREMEÑA GARANTIZADA');
INSERT INTO prestaciones (nombre)values ('SEGURO OBLIGATORIO DE VEJEZ');
INSERT INTO prestaciones (nombre)values ('SUBSIDIO MAYORES DE 52 AÑOS');
INSERT INTO prestaciones (nombre)values ('SUBSIDIO POR DESEMPLEO MAYORES 55 AÑOS');
INSERT INTO prestaciones (nombre)values ('VEJEZ SOVI NO COMUN');
INSERT INTO prestaciones (nombre)values ('VIUDEDAD');
INSERT INTO prestaciones (nombre)values ('FAV. FAMILIARES CON % VIUDEDAD (LEY 26/85)');
INSERT INTO prestaciones (nombre)values ('PENSION INCAPACIDAD PERMANENTE');
